### ISSUE TITLE
Uyghur styled hyphen

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [aliftype/amiri#100]
The Uyghur text has different shape for hyphen, which performanced as underscore. Is it possible of implementing this variant? This can be available via _locl_ feature.

This variant can be found everywhere when you go to Xinjiang, PR China. It can be found on their signboards, propagendas, ads and notices.

**Comment by khaledhosny** [comment]
According to the quote [here](https://lists.w3.org/Archives/Public/www-international/2014AprJun/0162.html), they are simply using the tatweel not the hyphen. Many applications allow selecting different hyphenation character.

**Comment by khaledhosny** [comment]
I can add a `local` variant, but I highly doubt that any application inserting an automatic hyphen at the end if line applies OpenType features to it, so it will only work for explicit hyphen which might not be desired.

**Comment by KrasnayaPloshchad** [comment]
According to [bug 85731](https://bugs.documentfoundation.org/show_bug.cgi?id=85731) at TDF Bugzilla LibreOffice has very limited support for hyphenation, so I suggest adding `salt` feature and using language tag `UYG` to work around that.

**Comment by KrasnayaPloshchad** [comment]
Kazakh text use this variant too.

**Comment by khaledhosny** [comment]
No going to do that unless someone can show me an application that supports this.
