### ISSUE TITLE
اقتراح بتغيير ألوان التشكيل للحمرة موافقه للمصاحف القديمة

### ISSUE THREAD

**Issue by munzirtaha** [aliftype/amiri#101]
كما ذكر علماؤنا أن الحمرة للحركات والتنوين والتشديد والتخفيف والسكون والوصل والمدّ وقد وجدتك أخي خالد تضع السكون بلون أرجواني خلاف بقية علامات التشكيل التي وضعت بلون أخضر مع أنه لا معنى لهذا التفريق، فأفترح لو تغير الألوان لتوافق اللون المستخدم منذ زمن أبي الأسود الدؤلي في هذا وهو اللون الأحمر (وليس الأرجواني) في الجميع

أما بالنسبة لعلامات الوقف والوصل فقد وضعت حاليا أيضا باللون الأرجواني ولو جعلتها بلون أزرق لتخالف علامات التشكيل لصارت أجمل وأوضح

**Comment by munzirtaha** [comment]
وهذا مثال لأحد المصاحف التي اعتمدت الألوان الأصيلة
![screenshot_20160721_202150](https://cloud.githubusercontent.com/assets/2936425/17032226/d4c2e070-4f80-11e6-8f52-74a9da86cf69.jpeg)

**Comment by khaledhosny** [comment]
لا أمانع في اعتماد ألوان مختلفة، الألوان الحالية لم تكن من اختياري لكن لا أظن الشخص الذي اقترحها يستخدمها حاليًا.

أحتاج قائمة برموز يونيكود و اللون المقترح لكل منها. يمكن أن يحتوي الخط أيضا على أكثر من لوحة ألوان، لكن لا أظن يوجد حاليًا طريقة لتغيير لوحة الألوان على الوب.

**Comment by munzirtaha** [comment]
مصحف سلطنة بروناي
http://library.tafsir.net/book/5859
جميع الحركات والعلامات باللون الأحمر باستثناء
علامة السجدة بلون أخضر
̅ u+305
علامات الوقف بلون أزرق:
ۖ u+6D6
ۗ u+6D7
ۘ u+6D8
ۙ u+6D9
ۚ u+6DA
u+6DBۛۛ

**Comment by khaledhosny** [comment]
I applied the requested changes. I did not give the colors much careful thought, but it should not be hard to try modifying the colors yourself and come up with better ones and send a pull request.

All the code that generates the color font is in `tools/makecolr.py` and the only dependency you need is https://github.com/behdad/fonttools. The colors and glyph groups are defined on the top of the file, and after modifying it you can run `make amiri-quran-colored.ttf` to build the font.

**Comment by munzirtaha** [comment]
رائع وأشكر لك سريع استجابتك وتوضيحك، سؤال: هل بالإمكان تغيير لون الهمزات جميعها أم أن هذا مستحيل باعتبار أن الألف والهمزة جزء واحد لا يتجزأ؟

**Comment by khaledhosny** [comment]
يمكن تغيير الهمزات، يمكنك فتح الخط في فونت فورج و معرفة اسم جزء الهمزة و إضافته إلى قائمة اللون المراد، أو أخبرني ما الحروف التي لم تلون همزاتها.
