### ISSUE TITLE
‫وجود ما يشبه السّن بين الكاف والهاء في "كهم"

### ISSUE THREAD

**Issue by SafaAlfulaij** [aliftype/amiri#102]
<div dir="rtl">
<img src="https://cloud.githubusercontent.com/assets/3509617/17176022/693be0a8-5413-11e6-94bc-083a476db1bc.png">
<br>
في حال كان حجم الخط صغيرا (20 مثلا) سيظهر الشكل كسنّ.
</div>

**Comment by khaledhosny** [comment]
![a](https://user-images.githubusercontent.com/93914/34178285-4e80d1cc-e50f-11e7-86b8-9f370c205995.png)
