### ISSUE TITLE
Large space before word that starts with kaaf (ك)

### ISSUE THREAD

**Issue by mustafa0x** [aliftype/amiri#105]
I often mistakenly assume that there are two spaces before it, but in reality there is just one wide space (almost double the width).

![kaaf](https://cloud.githubusercontent.com/assets/1473102/19266793/f1b2c178-8fb3-11e6-8385-ef7f9b45b292.png)

Clearly this is due to the elongated top stroke, so I'm not sure what the right solution here is.

**Comment by khaledhosny** [comment]
I can kern the kaf with space, but it might cause collisions on some cases, and (more importantly) it might degrade performance greatly on applications that cache shaping results per word like Firefox or Chrome (OpenType features involving space is incompatible with that caching mechanism so it will be disabled) and Amiri requires lots of OpenType processing so it benefits greatly from such cache.

**Comment by mustafa0x** [comment]
Also noticed this:

![kaaf-after-harakah](https://cloud.githubusercontent.com/assets/1473102/19861231/754eef30-9f94-11e6-8b26-46cc8cc24bb3.png)

The font is beautiful, I really enjoy it, and several my site visitors expressed similar feelings.

![default](https://cloud.githubusercontent.com/assets/1473102/19861386/007d722a-9f95-11e6-8352-640a28c8532d.png)

**Comment by khaledhosny** [comment]
What is the issue with اذكر?

**Comment by mustafa0x** [comment]
The sukoon is for the ذال but is above the ألف

Similarly:

![ss](https://cloud.githubusercontent.com/assets/1473102/20030492/09c9e718-a36f-11e6-8af6-16def0676144.png)

This is on my Mac, but I just checked and didn't get the same results using the web font in the browser.

It's probably not something that can be controlled by the Amiri font, then.

**Comment by khaledhosny** [comment]
Oh, Mac. I guess it is a bug in the Mac text layout engine, does it work in Firefox or Chrome (they use HarfBuzz not the system layout engine)?

**Comment by mustafa0x** [comment]
Yeah, it displays properly in Chrome and Firefox, so I guess that can be ignored.

**Comment by khaledhosny** [comment]
I might know how fix it, I had similar issues with Windows in the past but I think I fixed them. Let me check again.

**Comment by khaledhosny** [comment]
Unfortunately it does not look like the same old Windows issue, so I don’t know how to fix it. Right now your best bet is to report it to Apple and hope they will fix it.
