### ISSUE TITLE
Colored dots on U+067A ARABIC LETTER TTEHEH

### ISSUE THREAD

**Issue by dscorbett** [aliftype/amiri#107]
In Amiri Quran Colored, the dots of U+067A ARABIC LETTER TTEHEH are not colored. I assume it is an oversight because it is the only letter in that font with that pattern of dots.

**Comment by khaledhosny** [comment]
An oversight indeed, thanks for spotting it. Two oversights actually, this character shouldn’t have been encoded at all in this font as it is not used in Quran, I just need the glyph as a contextual alternate for U+062A ARABIC LETTER TEH.
