### ISSUE TITLE
Building with FontForge?

### ISSUE THREAD

**Issue by bateni** [aliftype/amiri#110]
Is it possible to build this font with `FontForge` instead of `Sort Mills`?  Your scripts for XITS load `fontforge` as a fallback.  I did not test whether they work or not, but here in Amiri font when I import `fontforge`, I get an error on `font.generateFeatureString`, which is not defined.

**Comment by bateni** [comment]
I had a hard time compiling `sortsmill-tools` on Mac OS X, but even when I installed it on Ubuntu, there was no `ffcompat` inside `sortsmill`.

**Comment by khaledhosny** [comment]
Building with FontForge is not possible unfortunately, its Python module is missing APIs that I use and there are many bug fixes needed for Amiri in sortsmill-tools without it the resulting font will be broken. You might have better luck using @graphicore’s https://github.com/graphicore/docker-sortsmill.

**Comment by khaledhosny** [comment]
Building with FontForge is possible now, and I might even make it build with only Python tools at some point in the future.
