### ISSUE TITLE
موضع الهمزة على نبرة المكسورة في خط القرآن

### ISSUE THREAD

**Issue by hubaishan** [aliftype/amiri#117]
موضع الهمزة على نبرة المكسورة في خط القرآن منخفضة جدا

**Comment by khaledhosny** [comment]
أرجو إعطاء أمثلة و ذكر البرمجيات المستخدمة و إصداراتها.

**Comment by hubaishan** [comment]
![2](https://cloud.githubusercontent.com/assets/2285457/22068219/62f938b4-dda5-11e6-88da-4eb356512035.png)

سورة فصات من نص القرآن الذي نشرتموه على جيتهب
برنامج فايرفوكس
