### ISSUE TITLE
المسافة بين الأسطر في برامج أدوبي ضيقة جدا

### ISSUE THREAD

**Issue by hubaishan** [aliftype/amiri#118]
المسافة بين الأسطر في برامج أدوبي ضيقة جدا مما يسبب تداخل الشكلات مع النص

**Comment by khaledhosny** [comment]
أرجو إرفاق صورة توضح المشكلة.

**Comment by hubaishan** [comment]
![ilistrator](https://cloud.githubusercontent.com/assets/2285457/22067937/605abbba-dda4-11e6-8e0a-b32e0c6da5af.png)
برنامج إليستراوتر cs6
حجم الخط 12

**Comment by khaledhosny** [comment]
أظن هذه أيضًا مشكلة في البرنامج. حسب الإعدادات الموجودة في ملف الخط فالمفروض في حجم ١٢ نقطة أن يكون الجزء المرتفع من السطر ٢١٫٧٦ نقطة، و الجزء المنخفض ٧٫٦١ نقطة، و بالتالي المسافة بين السطرين ٢٩٫٣٧ نقطة. هذه الإعدادات مختارة بعناية لتعطي مسافة معقولة لعلامات التشكيل و الوقف، لكن لا يبدو لي أن البرنامج يستخدمها كما يظهر من الصورة.

**Comment by khaledhosny** [comment]
ربما المسافة بين الأسطر في مضبوطة على قيمة ثابتة؟

**Comment by hubaishan** [comment]
لا هي على وضعية 
Auto

**Comment by khaledhosny** [comment]
لا أعرف ما مشكلته إذا.

**Comment by hubaishan** [comment]
تأكدت أن المشكلة من برامج أدوبي نفسها حيث أن وضعية المسافة بين الأسطر 
Auto 
تساوي =حجم النص *1.2
وذلك لا يتغير بنوع الخط وليس لبيانات الخط أي اعتبار في المسافة بين الأسطر

**Comment by khaledhosny** [comment]
شكرا لوصولك لأصل المشكلة. لا شيء نغيره في الخط إذًا.
