### ISSUE TITLE
Slope of exclamation mark ! in slanted variants

### ISSUE THREAD

**Issue by chrisgjohnson** [aliftype/amiri#120]
In slanted versions of Amiri, the exclamation mark ! appears to slant backwards (i.e. like "\\", rather than like "/" as I would expect). Is this intentional?

**Comment by khaledhosny** [comment]
It is supposed to stay upright, since supporting right slanting punctuation marks (for Latin) and left slanting (for Arabic) is broken in most web browsers. Looks like the exclamation mark was missed.
