### ISSUE TITLE
Overlapping diacritics

### ISSUE THREAD

**Issue by dscorbett** [aliftype/amiri#121]
In all six fonts, some diacritics overlap letters or other diacritics. Minimal test strings follow. The same pair of characters can have multiple test strings if they overlap in different ways. I found most of these by skimming the quran-data repo in Amiri Quran Colored.

Dammah & shaddah:
* ٯلُمّا

Dammah & sukūn:
* تُحۡمل
* ثُحۡمل
* لرُكۡىل

Fatḥah & fatḥah:
* أَلَّا
* أَىَد
* ىَّںَا

Fatḥah & hamzah:
* لىَأ

Fatḥah & maddah:
* لرَاۤ
* كمَاۤ

Fatḥah & shaddah:
* ىَىّٮ
* ٯلَمّا
* ىَىّٯ

Fatḥah & sukūn:
* تَحۡمل
* ثَحۡمل
* لرَكۡىل

Hamzah & jīm:
* ىٕج

High alif & kāf:
* ىىٰكى
* هىٰكم
* ىىٰكم

High mīm & alif:
* ىئَۢا
* ىـَۢا
* ىءَۢا
* عمَۢا
* ىمَۢا
* كمَۢا

High mīm & fatḥah:
* ىۢىَٮ
* ىۢىَا

Kasrah & ḥāʾ:
* لرِح
* ىٯِح
* إِح
* لىِح
* ىلِح
* ىىِح
* لِح

Kasrah & kasrah:
* لِإِ

Lām & maddah:
* لوۤ
* كلوۤ

Maddah & kāf:
* كاۤىكم

Maddah & shaddah:
* كاۤوّ
* كاۤىّو

Mīm & kasrah:
* ىكمِ
* ىلمِ

Mīm & kasratān:
* ىكمٍ
* ىلمٍ

Mīm & low mīm:
* مِۭ
* ىمِۭ
* ممِۭ

Mīm & open kasratān:
* ىكمࣲ
* ىلمࣲ

Rāʾ & yāʾ:
* ريں
* ىريں

Shaddah & kāf:
* ىدّكر

Shaddah & shaddah:
* ىّىّا

Wāw & kasrah:
* ولِله

Wāw & yāʾ:
* ىويس
* ويس

**Comment by KrasnayaPloshchad** [comment]
Filled #47

**Comment by mustafa0x** [comment]
ءَآلْـَٰٔنَ

Occurs twice in سورة يونس.

**Comment by khaledhosny** [comment]
> ءَآلْـَٰٔنَ
> 
> Occurs twice in سورة يونس.

Oh, this is completely broken! Though the correct spelling that works best in Amiri is ءَاۤلۡءَٰنَ. In general, for Unicode-encoded Quranic text that works best with Amiri, check https://github.com/khaledhosny/quran-data.

**Comment by mustafa0x** [comment]
بوركت.

I'm curious, is that spelling "valid"? In that, is that join one of the hamzah's joining rules?
