### ISSUE TITLE
Name of font-family in amiri.css is NoneWeb

### ISSUE THREAD

**Issue by AmrEldib** [aliftype/amiri#122]
In the latest release Amiri 0.109, the font-family in amiri.css is NoneWeb instead of AmiriWeb.  
I assume the value of `%(family)s` in [this line](https://github.com/alif-type/amiri/blob/master/tools/makecss.py#L18) is incorrect or null.

**Comment by khaledhosny** [comment]
This has been fixed with 3425c57cff7951a30ea6eab079e1648859864d2f already. I need to cut a new release.
