### ISSUE TITLE
CHROME : Italic not working with stand alone numbers

### ISSUE THREAD

**Issue by francisneedham** [aliftype/amiri#124]
Hi,
if i WRITE two numbers in italic ( ex. 12 ) italic won't be displayed.
If i Write two numbers with a leading char ( ex. a12 ) numbers will be in ITALIC.

any suggestions ?

thanks !

**Comment by francisneedham** [comment]
You can replicate the bug even on 
http://typecast.com/preview/google/Amiri

**Comment by khaledhosny** [comment]
Looks like an issue specific to chrome, need to investigate.

**Comment by khaledhosny** [comment]
This seems to be another manifestation of this chrome [bug](https://bugs.chromium.org/p/chromium/issues/detail?id=779374). If you really just want the Latin part of the font, you might want to try https://github.com/skosch/Crimson, since Amiri’s is Latin is basically a copy of it.
