### ISSUE TITLE
يتم تلوين الحركات بشكل غير صحيح

### ISSUE THREAD

**Issue by tarekeldeeb** [aliftype/amiri#125]
في تطبيق حي على الشبكة، اقوم باستدعاء الخط عن طريق

```
@font-face {
    font-family: Amiri Quran ColoredWeb;
    font-style: normal;
    font-weight: 400;
    src: url('../font/amiri-quran-colored.eot?') format('eot'),
         url('../font/amiri-quran-colored.woff2') format('woff2'),
         url('../font/amiri-quran-colored.woff') format('woff'),
         url('../font/amiri-quran-colored.ttf')  format('truetype');
}
```
مؤخرا لاحظت ان الحركات يتم تلوينها بالاخضر على غير مرادي وبشكل غير مفهوم
![font_bug](https://user-images.githubusercontent.com/90985/28672128-27b4343c-72df-11e7-98f4-b419ccfb26c2.PNG)

الاحظ الاتي:
- الحركات مع الهمز غير ملونة
- الشدة بها مشكلة
- الياء اللينة يتم تلوينها ايضا

**Comment by khaledhosny** [comment]
خط القرآن الملون يلون الحركات و بعض العلامات الأخرى (على البرمجيات التي تدعم التقنية التي يستخدمها). إذا كنت لا تريد التلوين فاستخدم خط القرآن غير الملون. مع هذا فالألوان في الصورة غير صحيحة، لذا أحتاج أن أعرف ما المتصفح المستخدم و إصدارته و إصدارة الخط، قد يفيد أيضا إعطاء رابط لصفحة وب بسيطة تظهر فيها المشكلة.

الألوان المضبوطة ينبغي أن تظهر كما في [هذه الصفحة](http://www.amirifont.org/fatiha-colored.html):
![screenshot-2017-7-28 amiri quran colored test](https://user-images.githubusercontent.com/93914/28696632-631e5f2e-733f-11e7-9841-c00dc724fca6.png)

**Comment by khaledhosny** [comment]
معرفة نظام التشغيل مهمة أيضا.

**Comment by tarekeldeeb** [comment]
شكرا على معلومة التلوين، قمت بتعديل وصف المشكلة 

نظام التشغيل : ويندوز 10
 57 المتصفح: كروم 
كلاهما 64 بت

اصدار الخط لا اعرفه، انا اقوم باستدعائه كما بالاعلى

الصفحة من برنامج متغير وغير مستقر، يمكنك مشاهدته هنا
http://is.gd/quranquiz

**Comment by khaledhosny** [comment]
أقترح أن تجرب آخر نسخة للخط من المستودع هنا لنرى إن كانت المشكلة موجودة فيها.

**Comment by khaledhosny** [comment]
أعتقد المشكلة أنك تستخدم نسخة قديمة من الخط، فالألوان في الصفحة التي أشرت إليها هي الألوان القديمة و قد كانت هناك مشكلة في الخط وقتها فعلا. لحل مشكلة الألوان إما أن تستخدم آخر نسخة من الخط أو تتفادى النسخة الملونة.
