### ISSUE TITLE
Alternate glyph for Meem

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [aliftype/amiri#127]
This variant will transformed Meem looks as this at the end of word:
![1](https://i.imgur.com/bm8zMXe.jpg)

Scheharazade have already making this variant available in Sindhi locale. However it’s not difficult in Amiri, the prefered shape can be found in U+FDFD.

**Comment by khaledhosny** [comment]
I’m yet to see any evidence about Sindhi preference for this meem variant. Actually SIL fonts are the only fonts to make this claim.

**Comment by KrasnayaPloshchad** [comment]
On Wikimedia Commons I found a photo took from book shop, all the books printed in Sindhi.
https://commons.wikimedia.org/wiki/File:Sindhi_Literature.JPG
Then I found ۾ showing this shape.

**Comment by khaledhosny** [comment]
Almost all instances of م or ۾ that I found in the image above use the form already in Amiri font. I’m even more convinced now that a locale variant is not needed.

**Comment by KrasnayaPloshchad** [comment]
So how to enable it?

**Comment by khaledhosny** [comment]
I meant it looks like the existing Amiri glyph for م or ۾, so no alternates are required.

**Comment by KrasnayaPloshchad** [comment]
I found it again in this image, in the word الم, second line:
https://en.wikipedia.org/wiki/File:Ahmet_Karahisari_001.jpg
