### ISSUE TITLE
Alternate glyph for Heh Doachashmee 

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [aliftype/amiri#128]
Heh Doachashmee has a variant in Sindhi, which written as ھ all the time.

**Comment by khaledhosny** [comment]
Do you have examples of such?

**Comment by KrasnayaPloshchad** [comment]
Seems found. On this photo I found several books shows this variant at the middle of the word.
https://commons.wikimedia.org/wiki/File:Sindhi_Literature.JPG

**Comment by khaledhosny** [comment]
The other form is also used, some fonts have medial ه that looks like a هـ, that is a stylistic choice not language dependent.
