### ISSUE TITLE
موضع النون الصغيرة العالية

### ISSUE THREAD

**Issue by linostar** [aliftype/amiri#130]
‮في خط **أميري-قرآن** في برنامج مايكروسوفت وورد على وندوز، تظهر النون العالية بهذا الشكل:
![capture3](https://user-images.githubusercontent.com/719022/32272405-916413ca-bf06-11e7-97f1-adf5df6ccefb.PNG)
‮الصور من اليمين إلى اليسار تُظهر الشكل: بلا كشيدة، مع كشيدة واحدة بين الضمة والنون العالية، مع كشيدتين، مع ثلاث كشيدات، مع أربع كشيدات، بالترتيب.

‮يُفترض بالنون العالية أن تكون منخفضة وتقع بعد الحرف لا فوقه، نحو ما في الصورة التالية:
![capture4](https://user-images.githubusercontent.com/719022/32272611-83e8bb46-bf07-11e7-83fc-b02ac7370107.PNG)

**Comment by khaledhosny** [comment]
ليست على كشيدة في كل المصاحف:
![image](https://user-images.githubusercontent.com/93914/32274015-9fb617fa-bf0d-11e7-9c23-a4ea96e56a45.png)

**Comment by khaledhosny** [comment]
![image](https://user-images.githubusercontent.com/93914/32274926-f293b1cc-bf11-11e7-8548-e2697749f978.png)

**Comment by linostar** [comment]
![](https://user-images.githubusercontent.com/93914/32274926-f293b1cc-bf11-11e7-8548-e2697749f978.png)
ما مصدر هذه الصورة؟

**Comment by khaledhosny** [comment]
من آخر تعديل في المستودع.

**Comment by linostar** [comment]
يبدو أن المشكلة كانت متعلقة بالمحرر. في كلّ من مايكروسوفت وورد و نوتباد++ على وندوز ظهرت النون مرتفعة، لكن في محرر فيجوال ستديو كود ظهرت منخفضة كما ينبغي.
