### ISSUE TITLE
Italic punctuation not correctly slanted

### ISSUE THREAD

**Issue by arthurattwell** [aliftype/amiri#131]
In the Google Fonts version of Amiri, the italic exclamation mark slants the wrong way, and other punctuation is upright, not slanted:

![amiri-google-font-italic-punctuation](https://user-images.githubusercontent.com/1053331/32365004-a5a531ae-c080-11e7-8837-510a5a0e2498.jpg)

In the latest version of the font in this repo, the exclamation mark is upright, and like other punctuation not slanted as they should be:

![amiri-latest-font-italic-punctuation](https://user-images.githubusercontent.com/1053331/32364940-5ff3dc1e-c080-11e7-86f1-22986183ba2b.jpg)

Sorry I don't have the skills to submit a fix myself! Let me know if it helps for users like me to nudge Google Fonts to update their version.

Thanks for this lovely font.

**Comment by khaledhosny** [comment]
The upright punctuation in italic styles is intentional; it is a valid typographic style (though a bit outdated) and is used here as a compromise since these characters are shared between Arabic and Latin, but our Arabic and Latin slant to opposite directions and getting these characters to slant conditionally based on context is tricky to get right in browsers.

You can use https://github.com/skosch/Crimson if your are looking for a Latin font, Amiri’s Latin is basically a copy of it.

**Comment by arthurattwell** [comment]
Thanks – that makes sense, and is a really interesting text-direction challenge! We have been using Amiri for [this project](http://www.core-econ.org/the-economy/), thinking we might later do an Arabic translation and could use the same font.

We do need the punctuation slanting with the text, though, so for now we'll probably switch to Crimson Text (Crimson would be closer, but we want to serve the font from a major CDN like Google Fonts, which doesn't serve Crimson), and if we do an Arabic translation we'll just use Amiri for the Arabic pages.

Do you happen to know whether Google Fonts is likely to update their version to your latest one, with the straight exclamation mark? Just curious.

**Comment by khaledhosny** [comment]
I need to cut a new release first, then Google Fonts will update their version at some point (they may take a while, though). Also note that the version of Crimson in Google Fonts is very outdated, see https://github.com/google/fonts/issues/284 and https://github.com/skosch/Crimson#naming-confusion (though the recommendation to use Amiri here might not be very well thought of 🙂).

**Comment by arthurattwell** [comment]
Thanks! I (and my [fellow designers](http://fireandlion.com/about/#our-team)) think of Crimson and Crimson Text as completely different typefaces, from a design perspective. It would be a problem if sites we've created with Crimson Text effectively started using the new Crimson. Anyway, that's a whole other discussion for another place.

**Comment by KrasnayaPloshchad** [comment]
OpenType has four feature tags can be used for this: `ltra`, `ltrm`, `rtla`, `rtlm`, so you can try to add at least one of them to make punctuation slanted for different direction.

**Comment by khaledhosny** [comment]
That is what I used, but implementations don’t handle them correctly for the digits.
