### ISSUE TITLE
InDesign - vowel postion on lafzul jalaalah

### ISSUE THREAD

**Issue by maaldheefee** [aliftype/amiri#132]
![image](https://user-images.githubusercontent.com/16198035/32500239-d2183ebc-c3e5-11e7-836f-2d44e3a7ad63.png)

The issue in present only with automatically placed vowels.

**Comment by khaledhosny** [comment]
Can you try the latest version in the repository?

**Comment by maaldheefee** [comment]
Issue is not present in v000.110. Thanks.
