### ISSUE TITLE
Can't Compile document in Windows

### ISSUE THREAD

**Issue by hubaishan** [aliftype/amiri#135]
Can't compile documentation-arabic.tex in windows Miktex/xelatex with amiri package installed I have this error
``` 
fontspec error: "font-not-found"
! 
! The font "amiri-regular" cannot be found.
! 
! See the fontspec documentation for further information.
! 
! For immediate help type H <return>.
```

**Comment by hubaishan** [comment]
I have fixed this issue by changing path in font definition to

`Path = ../,`

**Comment by khaledhosny** [comment]
The file is  usually compiled by `make doc` from the top directory, so the font setup is tailored for this.
