### ISSUE TITLE
الهمزة المفردة في وسط الكلمة بين حرفين يتصل أحدهما بالآخر

### ISSUE THREAD

**Issue by ameer4** [aliftype/amiri#137]
الهمزة المفردة في وسط الكلمة بين حرفين يتصل أحدهما بالآخر كما في "شيءا" عند إضافة كشيدة لها بعد الياء "شيـءا" يتم فصلها بدلاً من رسمها في الفراغ بين الحرفين.

**Comment by khaledhosny** [comment]
ما الغرض من الكشيدة هنا؟

**Comment by ameer4** [comment]
فقط لإكمال ما يستحسن إصلاحه
فالكشيدة استخداماتها لا حصر لها، كمثال في أبيات الشعر
