### ISSUE TITLE
High hamza incorrect spacing

### ISSUE THREAD

**Issue by hkmbs** [aliftype/amiri#138]
The high hamza joins with the alef in:

![default](https://user-images.githubusercontent.com/34926416/34426079-c36e1340-ec6d-11e7-9167-33381a07acc0.png)

(Jawi: ڤرکاتاٴن,perkataan, that means "word")
Whereas it should look more like

![default](https://user-images.githubusercontent.com/34926416/34426128-170cdd4c-ec6e-11e7-8877-65fd20fe14f0.png)

**Comment by khaledhosny** [comment]
This is already fixed in the repository. Will try to cut a new release soonish.
![](https://user-images.githubusercontent.com/93914/34435403-09202586-ec96-11e7-8612-1152f8e69c6c.png)
