### ISSUE TITLE
شكل البسملة في متصفح كروم مشوه بخطوط عرضية

### ISSUE THREAD

**Issue by tarekeldeeb** [aliftype/amiri#142]
عند فتح [الصفحة](http://www.amirifont.org/fatiha-colored.html) في متصفح كروم تظهر خطوط عرضية تشوه البسملة، لا توجد تلك المشكلة في متصفح اكسبلورر. 

هل المشكلة متجذرة في كروم ام يمكن حلها من الخط الاميري؟

**Comment by khaledhosny** [comment]
أتوقع مشكلة في كروم، لأنه على حد علمي يستخدم مكتبات النظام لرسم الخطوط الملونة من هذا النوع، وإذا كان إكسبلورر سليم (و هو يستخدم نفس المكتبات) فغالبا المشكلة تخص كروم.

**Comment by mustafa0x** [comment]
This only seems to happen on Windows.

**Comment by khaledhosny** [comment]
أقترح الإبلاغ عن الموضوع في كروم، لا أظنها مشكلة في الخط.
