### ISSUE TITLE
خط القرآن الملون يظهر باللون الاسود فقط على الهواتف

### ISSUE THREAD

**Issue by tarekeldeeb** [aliftype/amiri#144]
خط القران الملون يظهر بشكل جميل على الحواسيب بمختلف انظمة التشغيل
لكنه يظهر باللون الاسود دائما على الهواتف
تحققت من اندرويد و ايفون وكنت استخدم اخر اصدارات الخط الاميري

هل ملف التنسيق سي اس اس ينقصه شيء لتفعيل الالوان؟
هل الهواتف تدعم الالوان بداخل الفونت؟

**Comment by khaledhosny** [comment]
أندرويد لا يدعم الخطوط الملونة بالطريقة التي يستخدمها الخط الأميري، وكذلك آي.أو.إس

الإصدارة الأخيرة من ماك.أو.إس تدعم هذه الخطوط، لذا ربما يدعمها آي.أو.إس قريبا
