### ISSUE TITLE
Alternate comma & semicolon

### ISSUE THREAD

**Issue by hkmbs** [aliftype/amiri#145]
Jawi & Sindhi uses a different variant of the standard Arabic comma & semicolon that points downwards instead of upwards.

![2018-03-17 1 _li](https://user-images.githubusercontent.com/34926416/37553795-9a4ce6f6-2a09-11e8-9b76-e10525785fd1.jpg)

**Comment by khaledhosny** [comment]
I’ve seen this for Sindhi before, but it is the first time I hear about it for Jawi. Do you have any references for this?

**Comment by hkmbs** [comment]
Here's an example of the downward comma being used in Jawi. This is actually the common practice for Jawi.

![image](https://user-images.githubusercontent.com/34926416/37561528-6167bf46-2a8b-11e8-8f9c-337074297c11.png)

**Comment by hkmbs** [comment]
In fact, here is a newer excerpt of the downwards comma used in a Jawi/Malay newspaper.
![image](https://user-images.githubusercontent.com/34926416/37561577-89698e56-2a8c-11e8-8803-65b2cb5402dc.png)

**Comment by khaledhosny** [comment]
OpenType does not seem to have a language tag for Jawi https://docs.microsoft.com/en-us/typography/opentype/spec/languagetags, or may be I should use Malay tag? What language tag is used for Jawi text on the web?

**Comment by hkmbs** [comment]
I'm not sure, but it seems that Calibri uses locl: arab{MLY } for the commas.

**Comment by khaledhosny** [comment]
Thanks for the confirmation, I already did that.

**Comment by khaledhosny** [comment]
![Malay sample](https://user-images.githubusercontent.com/93914/37872187-871d6cbe-3002-11e8-8660-f5f5b2f708e6.png)

**Comment by hkmbs** [comment]
Nice, but it seems that there is no way to access that locale in Microsoft Word 2016 though. Do you have any idea how?

**Comment by khaledhosny** [comment]
I don’t use Word that much, but you need to set text language somehow (should be the language used for spell checking).

**Comment by hkmbs** [comment]
I checked and Jawi isn't on the list of text languages for spell checking for Word. Do you know of any other word processors that support Jawi?

**Comment by khaledhosny** [comment]
I checked LibreOffice but it does not allow Malay with Arabic script, but I’m checking if I can fix this. In the mean time, I think I’ll add a stylistic set so people can use this irrespective of the text language.

**Comment by hkmbs** [comment]
I think that's better. Thank you.

**Comment by khaledhosny** [comment]
FWIW, LibreOffice 6.1 (to be released in a few months) will provide two Jawi language settings, *Malay Arabic (Malaysia)* and *Malay Arabic (Brunei Darussalam)*, and it seems to activate the alternate glyphs when selected.

**Comment by KrasnayaPloshchad** [comment]
> Nice, but it seems that there is no way to access that locale in Microsoft Word 2016 though. Do you have any idea how?

For MS Word 2016, there are two Unicode characters can be used to present this:
U+2E41 REVERSED COMMA
U+204F REVERSED SEMICOLON
It would be nice if these characters were added in Amiri.
