### ISSUE TITLE
Using Alternative Glyphs?

### ISSUE THREAD

**Issue by techana** [aliftype/amiri#147]
Any hint please on how to use alternative glyphs, e.g. extended (swash) kaf [/aKaf.medi.alt] instead of the normal one?

Thank you.

**Comment by KrasnayaPloshchad** [comment]
I’ve found an instruction here occasionally, but it was written in Arabic.
https://github.com/alif-type/amiri/blob/master/documentation/Documentation-Arabic.pdf

**Comment by techana** [comment]
Thank you.

The document does not address the issue in hand, but provides useful info about the font.

As for the swash Kat, I just inserted the glyph in the text using its Unicode number (0x06AA
ڪ). The font does the shaping correctly based on the letter's position.

**Comment by khaledhosny** [comment]
There is currently no way to access the wide kaf except by using ڪ directly (though you shoudn’t do that unless your text is in Sindhi where ڪ is a distinct character from ك). I have been meaning to add a `jalt` feature for these wider glyphs, but never managed to do so.
