### ISSUE TITLE
Combinations of jīm, ḥā’ and khā’

### ISSUE THREAD

**Issue by techana** [aliftype/amiri#150]
When a jīm, ḥā’ or khā’ is combined with another letter, such as in the word برنامج, the shape of the letter gets out of proportion. I compared the digital Amiri font with the original one and found that the upper part of the letter (the crown) goes beyond its lower (curved) part; notice the red lines please in the attached image.

![amiri_comments](https://user-images.githubusercontent.com/10105658/38064723-4f9783ac-3308-11e8-9ed4-ea1b17006a79.png)

This can be fixed by pushing the upper part backward a little or pulling the lower part forward a little.

The spaces marked with cyan lines may also need fixing to match the original, but this could be a harder task!

On another matter, I noticed some missing combinations, such as the ones in words: الشيخ and التصحيح.  Let's hope more combinations will be added to the font in coming versions :)

Thank you.

**Comment by khaledhosny** [comment]
The images on top are not from the original typeface that Amiri is based on, which is the typeface used in Bulaq press roughly after 1910, not the older typefaces it had before.

There are no medial beh+final hah ligatures in Bulaq typecase, and for good reason; they look ugly:
![Bulaq typecase](https://user-images.githubusercontent.com/93914/38123932-86601ca6-33de-11e8-8b44-1f1dbf54d50c.jpg)
