### ISSUE TITLE
Improve and Support old fonts

### ISSUE THREAD

**Issue by M86xKC** [aliftype/amiri#152]
There are [so many Arabic fonts](https://sourceforge.net/projects/arabeyes/files/), that are no longer being developed and maintained (_Kacst fonts_, _Farsi fonts_ etc) some of them are pretty good and some have bugs that need to be fixed, but the bigger problem with these fonts is that they only support few scripts (only Arabic ?) so I thought maybe you can improve them and add support for other scripts, but if you don't have time I can do it with some help from you and other community members. The reason I don't like to do it is that I want `alif-type` to be a complete suite + I don't know a lot about Type design and Dev.

**Comment by khaledhosny** [comment]
Most these fonts are not available under Open Font License (OFL), which prevents mixing them with other OFL fonts (to get extra glyphs etc.). I don’t also have much free time myself, but if you (or someone else) want to start maintaining and fixing these fonts, I’ll try to help as much as I can.
