### ISSUE TITLE
النقطة في حرفي اللام والخاء المبتدئة

### ISSUE THREAD

**Issue by mjkujuk** [aliftype/amiri#153]
السلام عليكم دكتور خالد

هل من الممكن إضافة شكل آخر لحرف الخاء المتصل باللام الابتدائية بأن تكون نقطة الخاء من الداخل هكذا لخـ 
أي أن تكون نقطة الخاء بعد حرف اللام وليس قبله
وكذلك كافة أحرف الخاء المتصلة بحرف ابتدائي أيضا. 
شكرا لكم

**Comment by khaledhosny** [comment]
يمكن فصل الحرفين بإضافة [واصل صفر العرض](https://ar.wikipedia.org/wiki/%D9%88%D8%A7%D8%B5%D9%84_%D8%B5%D9%81%D8%B1_%D8%A7%D9%84%D8%B9%D8%B1%D8%B6) بينهما. بدون الواصل ”*الخارج*“:
![d](https://user-images.githubusercontent.com/93914/40267939-4f17d0fa-5b65-11e8-8452-07500311fd2c.png)

مع الواصل ”*ال‍خارج*“:
![zwj](https://user-images.githubusercontent.com/93914/40267944-702d4ebe-5b65-11e8-94cd-15a9625e9866.png)
