### ISSUE TITLE
الحركات

### ISSUE THREAD

**Issue by prof1993** [aliftype/amiri#154]
ارجو اطلاق اصدار آخر من الخط يجعل الحركات فوق الحرف مباشرة مثل خط لوتس مثلا، فهذا سيجعل الخط اكثر سهولة في النصوص المشكَّلة .فلا تبخل علينا بالنظر الى جمال هذا الخط الرائع

**Comment by khaledhosny** [comment]
لا خطة لهذا حاليا لأن تعديل موضع الحركات يتطلب وقتا وجهدا غير متوفرين عندي للأسف. الخط برخصة حرة تسمح بالتعديل وآمل أن يعدله أحد يوما ليناسب الأذواق المختلفة.
