### ISSUE TITLE
Overlapping Rohingya tones and vowels

### ISSUE THREAD

**Issue by dscorbett** [aliftype/amiri#155]
The Rohingya tone marks overlap the Rohingya vowel marks.

Tones:
* U+08EA ARABIC TONE ONE DOT ABOVE
* U+08EB ARABIC TONE TWO DOTS ABOVE
* U+08EC ARABIC TONE LOOP ABOVE
* U+08ED ARABIC TONE ONE DOT BELOW
* U+08EE ARABIC TONE TWO DOTS BELOW
* U+08EF ARABIC TONE LOOP BELOW

Vowels:
* U+064B ARABIC FATHATAN
* U+064E ARABIC FATHA
* U+08E4 ARABIC CURLY FATHA
* U+08E7 ARABIC CURLY FATHATAN
* U+064C ARABIC DAMMATAN
* U+064F ARABIC DAMMA
* U+08E5 ARABIC CURLY DAMMA
* U+08E8 ARABIC CURLY DAMMATAN
* U+064D ARABIC KASRATAN
* U+0650 ARABIC KASRA
* U+08E6 ARABIC CURLY KASRA
* U+08E9 ARABIC CURLY KASRATAN

دً࣪دَ࣫دࣤ࣬دࣧ࣪دٌ࣪دُ࣫دࣥ࣬دࣨ࣪دٍ࣭دِ࣮دࣦ࣯دࣩ࣭
![دً࣪دَ࣫دࣤ࣬دࣧ࣪دٌ࣪دُ࣫دࣥ࣬دࣨ࣪دٍ࣭دِ࣮دࣦ࣯دࣩ࣭](https://user-images.githubusercontent.com/1124347/40247537-c239c136-5a9a-11e8-91bd-1201fd0294d8.png)

**Comment by KrasnayaPloshchad** [comment]
Comparing to Scheherazade:
![default](https://user-images.githubusercontent.com/10364351/42042482-dacf1b2c-7b26-11e8-808a-916a9f264cf1.PNG)
