### ISSUE TITLE
Missing letter

### ISSUE THREAD

**Issue by hkmbs** [aliftype/amiri#156]
When using 'ss02', the letter "ج" disappears when I type "جسما". Only "سما" is visible. I used Word.

**Comment by khaledhosny** [comment]
Can’t reproduce this in other applications:
![ss02](https://user-images.githubusercontent.com/93914/40267982-da2e520e-5b65-11e8-9c68-9630574a82ca.png)

**Comment by hkmbs** [comment]
Here's a screenshot:
![2018-05-20 1 _li](https://user-images.githubusercontent.com/34926416/40274278-4d75cc20-5c05-11e8-9ddf-56ff78a770c4.jpg)
(Notice that it affects the word above it; "الكنز" becomes "لكنز" with the alif missing.)

**Comment by khalid-hussain** [comment]
I've tested this in Word 2016 (Windows 10) and was able to recreate it. However, I think it's restricted to Microsoft Word since it doesn't happen in Adobe InDesign and LibreOffice Writer.

**Comment by KrasnayaPloshchad** [comment]
I suggest reporting to Microsoft Community website.
