### ISSUE TITLE
Is the kerning from ikern included?

### ISSUE THREAD

**Issue by ghost** [aliftype/amiri#158]
I'm using the forked version of Crimson included in Amiri as advised by Sebastian Kosch. It's a pleasure to use it thanks to the build process so many thanks !
Is the kerning made by the ikern software included in the font ? In Kosch's repository there is an [ik folder](https://github.com/skosch/Crimson/tree/master/Source%20Files/ik) with ikern's kerning but it isn't present in Amiri.

**Comment by khaledhosny** [comment]
I don’t know/remember for sure, but the version I have should include whatever kerning Crimson had at the time of the fork which I think had iKern kerning applied and I cleaned.

**Comment by ghost** [comment]
Great ! Thank you for your answer.
