### ISSUE TITLE
zwj is visible

### ISSUE THREAD

**Issue by u-fischer** [aliftype/amiri#160]
I got a question how to avoid that with lualatex the zero width joiner (U+200D) is visible with some fonts, beside other with amiri. 

After digging a bit around I found the following code to patch the font. But as I know nothing about arabic typesetting I don't know if this is the correct method and if there is perhaps a more "official" way to do it. 

Could you enlighten me?

~~~~
\documentclass{article}
\usepackage{luacode}

\begin{luacode}

local patch_amiri = function (fontdata)
 if fontdata.fontname == "Amiri-Regular"
 then
   fontdata.characters[8205]["index"]=3
 end
end

luatexbase.add_to_callback
 (
  "luaotfload.patch_font",
   patch_amiri,
  "change_amiri"
 )
\end{luacode}

\usepackage{fontspec}
\setmainfont[Script=Arabic]{Amiri}

\begin{document}

\char"200Dي\char"200D

ي\char"200D

\char"200Dي

ي

\end{document}
~~~~

##  Output *without* the patch:

![image](https://user-images.githubusercontent.com/4047173/44959840-b7e10c80-aef5-11e8-91b7-ed3f0b340d32.png)

**Comment by khaledhosny** [comment]
The layout engine (LuaTeX here) should by default ignore the glyph outlines of ZWJ and other similar characters (like almost every other layout engine out there); for example HarfBuzz will use the space glyph after zeroing its width. If the layout engine has an option to show control characters, then in can use the glyph outlines.

**Comment by ralessi** [comment]
If you look at the [documentation of Scheherazade](https://software.sil.org/scheherazade/wp-content/uploads/sites/29/2016/03/Scheherazade-features-2.100.pdf) on p. 9, you will see that there is a feature id called `invs` (implemented in Graphite and seemingly available under xetex) which allows to either show invisible characters or hide them. I fully agree with @khaledhosny: it is better never to print the mark at any rate.  The only use one can possibly have of if would be to demonstrate something on screen or for debugging purposes.  In my opinion, that would leave two options, depending on what can be achieved: either always discard the glyphs of _all invisible characters_ listed in the documentation of Scheherazade, or provide some option to print them in case they should be needed.
