### ISSUE TITLE
Line hight issues.

### ISSUE THREAD

**Issue by OsamaAbbas** [aliftype/amiri#161]
السلام عليكم ورحمة الله.

دائمًا كنت أشعر أن ارتفاع السطر فيه مشكلة في الخط الأميري، يعني إذا تركنا ارتفاع السطر بقيمة 1، فغالبًا ما يحدث تداخل بين علامات التشكيل في السطر السفلي مع السطر العلوي.

وفي هذه الصورة:
![image](https://user-images.githubusercontent.com/3346502/45592778-c88f8900-b9b1-11e8-98bd-e2f05feef98d.png)
وهي من برنامج كروم، اخترت ارتفاع السطر 1.25، أو 125%. ومع ذلك تداخلت علامات التشكيل.

فالمطلوب معرفة ما ارتفاع السطر اللازم لمنع هذا التداخل؟
أو ضبط الخط بحيث يكون الارتفاع بقيمة 100% لا يحدث فيه تداخل، وهذا أفضل.

**Comment by khaledhosny** [comment]
<div dir="rtl">
القيمة 1 أو 100% لا تستخدم إعدادات ارتفاع السطر المضمنة في الخط، بل هي نسبة من مقاس الخط الحالي، فمثلا إذا كان مقاس الخط ١٢ نقطة تصبح المسافة بين السطور نفس القيمة.
</br>
لاستخدام إعدادات ارتفاع السطر المضمنة في الخط استخدم normal، لكن كل متصفح قد يترجمها إلى قيمة مختلفة، لذا لن تحصل على ارتفاع أسطر متسق بين المتصفحات وأنظمة التشغيل المختلفة.
</br>
على كل، لا يوجد ارتفاع سطر يناسب كل النصوص والتصاميم، وعليك اختيار القيمة المناسبة لك. شخصيا استخدم 1.5 للنصوص غير المشكلة أو قليلة التشكيل، و 2.5 للنصوص المشكلة.
<div>

**Comment by OsamaAbbas** [comment]
برنامج مثل جوجل دوكس ليس فيه القيمة
normal.
فلذلك سألت عن القيمة المضمنة في الخط.

كذلك فالمشكلة أوضح في الطباعة، فالقيمة 2.5 كبيرة جدا، وأذكر أني نظرت مرة في كتاب قديم مصفوف بالخط الأميري، وحاولت كتابة نفس النص بنفس عدد الكلمات في كل سطر بنفس عدد الأسطر في كل صفحة، وأقرب شيء وصلت إليه كان الحجم ١٦ بمسافة 1.5. أيضا في جوجل دوكس.

**Comment by OsamaAbbas** [comment]
القيمة
normal
على كروم، تبدو مساوية للقيمة 1.8.

وعند إدخال 1.8 في جوجل دوكس، يختفي التداخل ظاهريًّا كما يبدو هنا:
![image](https://user-images.githubusercontent.com/3346502/45593620-0e098180-b9c5-11e8-853c-5fd8003503c1.png)

ولكن عند تظليل كلمة من السطر العلوي، يتبين إن التداخل ما زال موجودًا:
![image](https://user-images.githubusercontent.com/3346502/45593616-04801980-b9c5-11e8-82d9-38ab61ffd445.png)

وليس الحال كذلك في خطوط أخرى، حتى مع القيمة 1، يعني حتى مع تظليل النص: الصندوق (إن صحت التسمية) الذي يتم تظليله لا يتداخل مع السطر السفلي أبدًا، فهذا خط ترادشنال أرابيك مع الارتفاع 1:
![image](https://user-images.githubusercontent.com/3346502/45593657-aa338880-b9c5-11e8-8938-8f58a00daeff.png)

فما السبب في هذه المشكلة؟

**Comment by OsamaAbbas** [comment]
الظريف أن خط ترادشنال، في نسخته الحديثة، ظهرت فيه مشكلات جديدة لم تكن موجودة من قبل:
![image](https://user-images.githubusercontent.com/3346502/45593685-5d03e680-b9c6-11e8-9591-ca52f10e16df.png)
ولا تسمح رخصته بإصلاحه للأسف.

**Comment by khaledhosny** [comment]
لا أظن للتظليل علافة بالمسافة بين الأسطر ولا علم لي من أين يأخذه المتصفح.
