### ISSUE TITLE
Numbers are not Italicizing

### ISSUE THREAD

**Issue by RB-Rhythm** [aliftype/amiri#164]
For some reason in Chrome, numbers will not show up as Italic unless there is a letter attached.

For example:
$1,500,000 will not italicise, where $1,500,000's will. 
The font looks to be working on Safari and Firefox. I was not able to test on IE as of the time of this post. 

We are using the google hosted version of the font. You can reproduce the issue within the styles samples here: https://fonts.google.com/specimen/Amiri

I'm running - Google Chrome: Version 69.0.3497.100 (Official Build) (64-bit)

**Comment by ewohlken** [comment]
+1

**Comment by khaledhosny** [comment]
Works fine here with Firefox on Linux (GitHub is failing to upload a screenshot). Also the version on Google Fonts is outdated https://github.com/google/fonts/issues/1426.
