### ISSUE TITLE
Support for Cyrillic

### ISSUE THREAD

**Issue by yellowfour** [aliftype/amiri#168]
Please consider to add support for Cyrillic letters. The Latin letters have reached perfection that other fonts can't come close to. So I'd like to use this single font file for both Latin and Cyrillic.

**Comment by khaledhosny** [comment]
Sorry, but Cyrillic is currently out of scope. The Latin glyphs in Amiri are originally from [Crimson](https://github.com/skosch/Crimson) which I believe support Cyrillic, so you might want to give it a try.
