### ISSUE TITLE
الضبط بالنقط

### ISSUE THREAD

**Issue by anasram** [aliftype/amiri#171]
<div dir="rtl">

أحاول استخدام المحارف التالية `U+FBB2-FBBE`:

﮲﮳﮴﮵﮶﮷﮸﮹﮺﮻﮽﮾

لتشكيل الأحرف وفق المذاهب القديمة للضبط، لأغراض بحثية.

السؤال:

1. أليست وظيفة هذه المحارف هو ضبط الأحرف بدلاً من علامات الضبط المعروفة اليوم، كالفتحة والضمة؟
2. إن كان الجواب بالإيجاب، فيبدو أن هذه المحارف لا تؤدي المهمة كما يجب. لاحظ:

![(غفور﮲ا رحيم﮲ا﮴)](https://user-images.githubusercontent.com/12219238/55877880-d736cb00-5ba3-11e9-86cf-8ba062728199.png)

(نصياً: غفور﮲ا رحيم﮲ا﮴)

1. فالنقط لا تظهر فوق الحرف مباشرة بل بعده.
2. تفصل بين الحروف المتصلة.

بالطبع هذه المسألة لا تشكل أولوية بالنسبة لمعظم المستخدمين، لكنني آثرت التنويه إليها على كل حال.

</div>

**Comment by khaledhosny** [comment]
<div dir="rtl">
للأسف لا. يونيكود ترفض إضافة نقاط تعمل كعلامات التشكيل التي يمكن إضافتها للحروف، وهذه النقاط في يونيكود هي رموز مستقلة لتستخدم في الأغراض التعليمية (ليمكن مثلا الإشارة إلى النقاط مستقلة عن أي حرف). راجع هذا النقاش على تويتر:
</div>

https://twitter.com/roozbehp/status/1105836899351052288

**Comment by anasram** [comment]
<div dir="rtl">
ممم، طيب ألا توجد طريقة التفافية workaround تسمح بوضع نقط معينة (بواسطة تلك النقاط أو غيرها) فوق الأحرف العربية؟
</div>

**Comment by khaledhosny** [comment]
<div dir="rtl">
إذا كنت تقصد نقاط الإعراب، فعلامات التشكيل الحالية ما هي إلا صورة من صورها والنقاط القديمة (الملونة) صورة أخرى، لذا يمكن مثلا تصميم خط يحتوي نقاطا بدل الضمة والفتحة إلخ. لكن ١) تحتاج هذه النقاط أن تكون ملونة وإلا اختلطت مع نقاط الإعجام ٢) لا أظن استخدام نقاط الإعراب مناسب لخط النسخ إذ لا قرينة تاريخية لذلك، لذا الأفضل أن يكون الخط كوفيا.
</div>

**Comment by anasram** [comment]
<div dir="rtl">

> والنقاط القديمة (الملونة) صورة أخرى، لذا يمكن مثلا تصميم خط يحتوي نقاطا بدل الضمة والفتحة إلخ

مداخلتي هنا لغاية أبسط من ذلك بكثير، فكل ما أريده هو توليد صورة تبين طريقة الضبط القديمة بالنقط، وإن تعذر العثور على حل _نصي بسيط_، فيمكن اللجوء لبرامج تحرير الصور لهذه الغاية. لكني أحببت الاستزادة من خبرتك في هذه المسألة.

 > الأفضل أن يكون الخط كوفيا.

هذه ملاحظة هامة وسأعمل بها، شكراً لك.
</div>

**Comment by anasram** [comment]
<div dir="rtl">
وجدتها:

غفور۬ا۬ رحيم۬ا۬۬

المحرف هو: `U+06EC ۬  ARABIC ROUNDED HIGH STOP WITH FILLED CENTRE`.
</div>
