### ISSUE TITLE
Add the 𝚏𝚛𝚊𝚌 feature for Indic-Arabic digits

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [aliftype/amiri#175]
With this feature enabled any cluster as ١/٢ would transformed as diagonal fraction, which should looks like this:
![1](https://user-images.githubusercontent.com/10364351/59690904-b5744880-91d1-11e9-97b1-030197c1a045.PNG)

This is inspired by #150.

**Comment by khaledhosny** [comment]
We already have `numr` and `dnom` features for fractions, `frac` is intentionally not supported because there is no consistency in implementing this feature across fonts.
