### ISSUE TITLE
What's the AmiriQuranColored.ttf for?

### ISSUE THREAD

**Issue by RasheedAZ** [aliftype/amiri#176]
Question: What's the AmiriQuranColored.ttf for? I thought it was for making the harakaat colour different from the text but is there any way to do this in LibreOffice?

**Comment by khaledhosny** [comment]
It only works in application that support this feature. It works in Firefox and Chrome, and macOS applications that use the system graphics API on latest OS versions, and LibreOffice on Linux with latest FreeType and Cairo libraries.

**Comment by RasheedAZ** [comment]
Salaam brother. Sorry for opening this again.

I've managed to install an Ubuntu based Linux with LibreOffice. How do I change the tashkeel to a colour different from the font?
