### ISSUE TITLE
Arabic thousands separator in Amiri appears to be inverted

### ISSUE THREAD

**Issue by Etewilak** [aliftype/amiri#179]
The Arabic thousands separator in Amiri resembles a left single quotation mark. According to The Unicode Standard, Version 12.1, the Arabic thousands separator must resemble an apostrophe, or a right single quotation mark.

**Comment by khaledhosny** [comment]
There are many shapes of the Arabic thousands separator, and the one I use is the form used by the historical Bulaq Press:
![IMG_20191021_202019](https://user-images.githubusercontent.com/93914/67232017-bc8dba80-f440-11e9-9fd4-43a631216548.jpg)
