### ISSUE TITLE
تداخل نقطة حرف الجيم في كلمة الحجى او الحجي

### ISSUE THREAD

**Issue by HiTuX** [aliftype/amiri#180]
لاحظت تداخل نقطة حرف الجيم مع *ي* أو *ى* كما في كلمة الحجى حين كتابها معرفة بـ ال
![2](https://user-images.githubusercontent.com/6303262/67302178-683e1580-f4e8-11e9-9cd2-440c9678ddf0.jpg)

**Comment by khaledhosny** [comment]
Duplicate of #192
