### ISSUE TITLE
Incorrectly Placed Brackets in Latin Alphabet

### ISSUE THREAD

**Issue by teewz** [aliftype/amiri#181]
Thank you for your improvements to Crimson.
Would it be possible to have bracket placement and sizes appropriate for latin alphabet text, maybe as an alternative?

See picture below as an example, I included Crimson and Minio Pro as a comparison.

![Asset 5](https://user-images.githubusercontent.com/1348631/68543626-e3913980-03b9-11ea-9e75-987dcba0f1b9.png)

**Comment by khaledhosny** [comment]
They are designed for Arabic. I can added Latin-specific variants, but applications don’t always consistently support this.
