### ISSUE TITLE
[question] How to use the AmiriQuranColored font?

### ISSUE THREAD

**Issue by RasheedAZ** [aliftype/amiri#182]
As you advised, I've managed to install an Ubuntu based Linux with LibreOffice. 

How do I change the tashkeel to a colour different from the font?

_Originally posted by @RasheedAZ in https://github.com/alif-type/amiri/issues/176#issuecomment-564363408_

**Comment by khaledhosny** [comment]
The colors are defined inside the font file and LibreOffice (or any other application, as far as I know) does not provide a way to override them.

**Comment by RasheedAZ** [comment]
Sorry I understood from this that you can. So again what is the whole point of AmiriQuranColored?
> 
> 
> It only works in application that support this feature. It works in Firefox and Chrome, and macOS applications that use the system graphics API on latest OS versions, and LibreOffice on Linux with latest FreeType and Cairo libraries.
_Originally posted by @khaledhosny in https://github.com/alif-type/amiri/issues/176#issuecomment-506989634_

**Comment by khaledhosny** [comment]
If the application supports the font you get colored glyphs, if it doesn’t you get uncolored glyphs. I didn’t say you can change the colors.

**Comment by RasheedAZ** [comment]
Oh sorry I misunderstood. I know it's not directly related to this project but do you know if there's any way to achieve this - I mean having the diacritics in a different colour?

**Comment by khaledhosny** [comment]
You can do this in Firefox and MS Office, but not in LibreOffice.

**Comment by RasheedAZ** [comment]
OK thanks really appreciated.
