### ISSUE TITLE
How to use the AmiriQuranColored font with xelatex?

### ISSUE THREAD

**Issue by javadr** [aliftype/amiri#183]
Hi Brother Khaled,
I wanted to use the font with xelatex, but it didn't work for me. 
Is it possible to use it with xelatex or not?
My MWE is here:

```latex
\documentclass{article}

\usepackage{xepersian}
\settextfont{Amiri Quran Colored}

\begin{document}
سلامٌ علَیکم وَ رَحمةُ الله و بَرَکاتُهُ
\end{document}
```

and the output looks like below:
![Screenshot from 2019-12-11 17-26-15](https://user-images.githubusercontent.com/1178221/70627379-61f02e00-1c3b-11ea-8db5-263d357e2449.png)

**Comment by khaledhosny** [comment]
XeTeX does not support color fonts.

**Comment by javadr** [comment]
Thanks for your fast reply. 
Is there any TeX-based engine capable of rendering the colored font?

**Comment by khaledhosny** [comment]
The latest versions of LuaTeX. Please ask on https://tex.stackexchange.com if you need further help.

**Comment by javadr** [comment]
Thanks. Please see https://tex.stackexchange.com/questions/520182
