### ISSUE TITLE
تداخل الحركات في لفظ الجلالة

### ISSUE THREAD

**Issue by munzirtaha** [aliftype/amiri#184]
في لفظ الجلالة إذا كانت اللام مفتوحة فإنها تتداخل مع الشدة
![amiri-bug](https://user-images.githubusercontent.com/2936425/70868883-ae19d600-1f8d-11ea-9724-4492cabe8c13.png)
أيضا أحب أن أسأل هل مخالفتك لمعيار يونيكود في قضية إضافة الشدة والألف الصغيرة تلقائيا عن عمد؟
أعني الاختبار أدناه
https://w3c.github.io/alreq/gap-analysis/tests/ligation/ligation_000.html

**Comment by khaledhosny** [comment]
> أعني الاختبار أدناه
https://w3c.github.io/alreq/gap-analysis/tests/ligation/ligation_000.html

لا أعرف من أین أتت هذه الصفحة بالنتیجة التی تتوقعها، لكن یونیكود لا تحدد شیئا بهذا الشأن ولا هی وظیفتها. أمیری خط نسخی طباعی ویتبع هنا التقالید المتبعة فی الخطوط النسخیة، ویضیف علیها تفادی شكل لفظ الجلالة فی المواضع غیر المناسبة.

**Comment by munzirtaha** [comment]
Let me quote this text which I believe relevant from the Unicode Standard 13.0 p. 388

> U+FDF2 arabic ligature allah isolated form is a very common ligature, used to dis-
> play the name of God. When the formation of the allah ligature is desired, the recom-
> mended way to represent the word would be <alef, lam, lam, shadda, superscript alef, heh>
> <0627, 0644, 0644, 0651, 0670, 0647>. In non-Arabic languages, other forms of heh, such as
> heh goal (U+06C1), may also form the ligature. Extra care should be taken not to form the
> ligature in the absence of the shadda and the superscript alef, as the sequences <alef, lam,
> lam, heh> and <alef, lam, lam, shadda, heh> exist in Persian and other languages with dif-
> ferent meanings or pronunciations, where the formation of the ligature would be incorrect
> and inappropriate.

So, my understanding is this feature shouldn't be enabled by default for Persian and similar non-Arabic languages. You are one of the few experts in these kind of topics so research it and give us  your final conclusion in a detailed way so it can be considered as a reference for further discussion in this particular issue.

**Comment by khaledhosny** [comment]
Amiri already tries to limit the ligature to [certain sequences](https://www.amirifont.org/documentation/Documentation-Arabic.html#%D9%84%D9%81%D8%B8-%D8%A7%D9%84%D8%AC%D9%84%D8%A7%D9%84%D8%A9), and enabling the ligature by default is the expectation of our users and Arabic typography in general regardless of this recommendation. I have seen almost zero occurrences of the sequence <alef, lam, lam, shadda, superscript alef, heh> out in the wild, and users of Amiri wouldn’t appreciate not having it by default.

**Comment by munzirtaha** [comment]
I agree but since glyph substitution (GSUB) could be defined per language, why not allow Arabic users to have the same experience where as others would have theirs.

**Comment by khaledhosny** [comment]
Because no one complained in 10 years, so I don’t see why I should make such a drastic change over a hypothetical issue. Either the issue does not exit or no one is bothered by it or Amiri isn’t widely used enough where this happens.
