### ISSUE TITLE
Change the shape of mark over ځ

### ISSUE THREAD

**Issue by khaledhosny** [aliftype/amiri#185]
https://www.unicode.org/L2/L2001/01316-Kaf-Sign-Proposal.pdf

**Comment by moyogo** [comment]
Check the shape of the mark in [کابل, no. 465](https://www.wdl.org/fr/item/13388/), 1958.

**Comment by khaledhosny** [comment]
It seems that the title (seems to be hand-written) use a hamza shape like Amiri has, while the body text uses the samll kaf sign like in the linked proposal. This suggests both are acceptable, but we might be reading too much into it .

**Comment by khaledhosny** [comment]
Since no one complained, I’m leaving it the way it is now.
