### ISSUE TITLE
منع توضع الحركات فوق الأحرف غير العربية

### ISSUE THREAD

**Issue by anasram** [aliftype/amiri#188]
<div dir="rtl">
سلامات خالد،

هل يمكن منع تركيب الحركات على الأحرف التي قبلها إن لم تكن تلك الأحرف أحرفاً عربية خالصة؟

هذا القيد يفيد في حالتين:

* عندما أريد _التكلم_ عن الحركات؛ لا استخدامَها، كأن أقول مثلاً: "ولا تلتقي أي من الضمة (ُ) أو الفتحة (َ) أو الكسرة (ِ) معاً في حرف واحد". سأضطر هنا لاستخدام محرف إضافي كالكشيدة مثلاً لبيان الحركات للقارئ: (ــُـ) و(ــَـ) و(ــِـ).
* في سياق عمليات البحث والاستبدال: كأن أعمل على استبدال فتحة بضمة: `s/َ/ُ/g`

سيكون من الأفضل لو ظهرت كل منها —في الحالتين— كحرف مستقل؛ على النحو التالي مثلاً:

![Free Arabic Distinct](https://user-images.githubusercontent.com/12219238/80861221-bdb46580-8c75-11ea-8737-b63d59dadc98.png)

</div>

**Comment by khaledhosny** [comment]
<div dir="rtl">

في الحالة الأولى يونيكود تنصح بوضع العلامة فوق مسافة ( َ)، أو يمكنك استخدام [الدائرة المنقطة](https://en.wikipedia.org/wiki/Dotted_circle) ◌َ.

في الحالة الثانية الفكرة وجيهة لكن لا أظن يمكن تطبيقها بشكل يعتمد عليه، فقد يكون الحرف قبل علامة التشكيل في جزء اتجاهه مختلف وفي هذه الحالة لا يمكن تطبيق قواعد الخط.

**Comment by anasram** [comment]
> <div dir="rtl">فقد يكون الحرف قبل علامة التشكيل في جزء اتجاهه مختلف</div>

<div dir="rtl">

يكفي أن تكون الفكرة صالحة للتطبيق في سياق أحرف ASCII على الأقل، فالغاية هنا أن تعمل في سياق التعليمات البرمجية فحسب.

</div>

<div dir="rtl">

مع جزيل الشكر والتقدير لجهودك سلفاً وخلَفاً :)

</div>

**Comment by khaledhosny** [comment]
<div dir=rtl>
المشكلة أنها ستعمل أحيانا وأحيانا لا، وفي رأيي هذا أسوأ من عدم عمل شيء.

**Comment by anasram** [comment]
<div dir="rtl">
ولم لا تقول: ما لا يُدرَك كله لا يُترَك كله؟ 🙃
</div>
