### ISSUE TITLE
علة في التشكيل على الحروف ذات الموضع المرتفع أو النازل

### ISSUE THREAD

**Issue by mkrbu50** [aliftype/amiri#193]
السلام عليكم ورحمة الله وبركاته،

هناك علّة عند وضع التشكيل على الرسمات المختلفة لحرف الألف فإن التشكيل يختفي أو يبترع لارتفاع موضعها عن السطر. 
نفس الشيء يحصل عند وضع كسرة تحت حرف ذات رسمة نازلة مثل حروف ج ح خ غ ع ر ز وغيرها إذا كانت منفردة.

شكراً لكم.

**Comment by khaledhosny** [comment]
في أي برنامج يحدث هذا؟

**Comment by mkrbu50** [comment]
على الأغلب في برنامج مايكروسوفت وورد.

**Comment by khaledhosny** [comment]
<div dir="rtl">

هذه مشكلة في بزامج ميكروسوفت ولا حل لها، إصلاحها في برنامج يفسد شيئا في برنامج آخر. جرب زيادة ارتفاع السطر.
