### ISSUE TITLE
Webfonts for version 0.113?

### ISSUE THREAD

**Issue by Cophla** [aliftype/amiri#195]
**Dear Mr. Khaled,** 
Thanks for your effort 
in the release 0.113 you missed the web fonts files?

**Comment by khaledhosny** [comment]
I intentionally stopped generating them to simplify the build.

**Comment by Cophla** [comment]
can i have the instructions, so i can generate them because i do not use google fonts and use your web fonts builds in websites i make

**Comment by KrasnayaPloshchad** [comment]
So you can try to convert via online services, such as Transfonter, OnlineFontConverter.com and so on.

**Comment by Cophla** [comment]
![Untitled](https://user-images.githubusercontent.com/16767283/88452185-47369680-ce65-11ea-81e1-60a56a0ff8dd.png)

Files Generated using: https://transfonter.org/

**Comment by KrasnayaPloshchad** [comment]
Oh I’ve seen someone collected a set of online conversion service in a forum, which of them is nice?
https://www.v2ex.com/t/459650
