### ISSUE TITLE
06AB ګ should be based on kehe 06A9 ک instead of kaf 0643 ك

### ISSUE THREAD

**Issue by moyogo** [aliftype/amiri#196]
Despite the name of the character "ARABIC LETTER KAF WITH RING", 06AB ګ is in the GAF shaping group like 06A9  in [ArabicShaping.txt](https://www.unicode.org/Public/13.0.0/ucd/ArabicShaping.txt):
```
06A9; KEHEH; D; GAF
[...]
06AB; KEHEH WITH ATTACHED RING BELOW; D; GAF
```

I don’t know any other font that does what Amiri currently does.
<img width="100" alt="image" src="https://user-images.githubusercontent.com/1923747/88919031-5ac96f00-d262-11ea-913d-b1270e18c830.png">

Was there a particular reason this was done this way?

**Comment by khaledhosny** [comment]
Hmm, it used to be Gaf-like then I changed it in a2c4de708d2b47afb5fb95e28faa48e2d0da6487. I don’t remember what I got that from, but either TUS or annotations say (said) that Kaf form is acceptable and I picked that, probably because back then my default Gaf was the Ottoman form (now `ss04`) which often colloids with previous letters so I wanted as little Gaf-like glyphs as possible.

**Comment by moyogo** [comment]
You’re right. I should have checked the [Arabic chart](https://www.unicode.org/charts/PDF/U0600.pdf), it says:
> may appear like an Arabic KAF (0643 &#x0643;) with a ring below the base

I guess Unicode is being inconsistent with how this one is encoded compared to the pairs &lrm;ݢ/ڬ, &lrm;ݣ/ﯓ, etc.
Thanks!

**Comment by moyogo** [comment]
On second thought, maybe the kaf-like form is historical, it’s not clear if it is used in Pashto nowadays.

**Comment by moyogo** [comment]
After looking at Pashto calligraphy videos online, it seems the Pashto kaf ک can alternatively be shaped like ك in final form, with 06AB ګ probably doing the same. It’s not clear if this happens in isolate form.

**Comment by khaledhosny** [comment]
I’m inclined to use the Gaf-like form, and make `ss04` use the Kaf-like form for all these glyphs.
