### ISSUE TITLE
علامتا التنصيص

### ISSUE THREAD

**Issue by wldwa19** [aliftype/amiri#197]
أين هما علامتا التنصيص الهلاليتين؟

**Comment by khaledhosny** [comment]
علامتي «» تأخذان الشكل الهلالي مع النص العربي

**Comment by wldwa19** [comment]
فعلًا، يحدث هذا تلقائيا في برامج مثل پَيْجَزْ وسْكْرِڤْنَرْ ولكن ليس في مَلَلْ
Pages/Scrivener/Mellel
لماذا؟

**Comment by khaledhosny** [comment]
لا علم لي، لكن على الأغلب عيب في البرنامج
