### ISSUE TITLE
00AD (hyphen) missing in TTF files

### ISSUE THREAD

**Issue by swatteau** [aliftype/amiri#199]
Thank you for this awesome font.

I noticed that commit [a402efa](https://github.com/alif-type/amiri/commit/a402efad555e77730fa2f43763e77138310561b3) introduced hyphenation problems when using the TTF files with ConTeXt (I haven't tried with LaTeX or any other TeX engine). Since this commit, the hyphen character is not printed anymore. Note that this problem does not occur when using the OTF files instead.

**Comment by khaledhosny** [comment]
That is a bug in ConTeXt, U+00AD is a control character not a graphical one and need not have a glyph in the font. Hyphen is either U+002D HYPHEN-MINUS or (more preferably) U+2010 HYPHEN.
