### ISSUE TITLE
التشكيل

### ISSUE THREAD

**Issue by hatemibrahim1410** [aliftype/amiri#200]
جزاكم الله خيرًا، وشكر الله لكم،،،
إن أمكن إضافة خاصية إضافة نوعين من التشكيل على الحرف الواحد
![Screenshot_1](https://user-images.githubusercontent.com/71362757/93287649-50474280-f7da-11ea-9251-ca9619509edc.png)

**Comment by khaledhosny** [comment]
أَِ أَُِ أَ أُ أَُ بَُ بَّ بَْ بِ‌َْ
<img width="516" alt="image" src="https://user-images.githubusercontent.com/93914/93349288-97175580-f837-11ea-831a-d2d163904e4e.png">

**Comment by hatemibrahim1410** [comment]
شكرًا على الاهتمام هذه الأمثلة من أي نسخة ؟؟

**Comment by hatemibrahim1410** [comment]
هذه النتيجة التي تظهر عندي في النسخة الأخيرة من الخط 0.113
![Screenshot_2](https://user-images.githubusercontent.com/71362757/93353435-38a0a600-f83c-11ea-8b04-ce30366c22e8.png)

**Comment by khaledhosny** [comment]
من النسخة الموجودة على هذا المستودع، انظر الملفات فی الصفحة الرئیسیة.

**Comment by hatemibrahim1410** [comment]
حضرتك تقصد هذه النسخة ؟؟
https://github.com/alif-type/amiri/releases/tag/0.113

**Comment by hatemibrahim1410** [comment]
إن أمكن أرسل لي ملف
ttf
مباشرة الذي فيه هذه الخاصية؛
فالملف الأخير 0.113 ليست فيه هذه الخاصية وتظهر على دوائر بعد الحرف !!
![Screenshot_2](https://user-images.githubusercontent.com/71362757/93353462-40604a80-f83c-11ea-8247-b825501040be.png)

**Comment by hatemibrahim1410** [comment]
إن أمكن أرسل لي ملف
ttf 
مباشرة،
فالنسخة الأخيرة لا تظهر بهذا الشكل، بل تكون بعد الحرف على دائرة:
![Screenshot_2](https://user-images.githubusercontent.com/71362757/93353763-96cd8900-f83c-11ea-9152-355d7ce6dc50.png)

**Comment by khaledhosny** [comment]
<div dir="rtl">

يمكن الحصول على آ خر نسخة من أی ملف بالنقر علیه فی صفحة المستودع الرئیسىة، مثلا:
https://github.com/alif-type/amiri/blob/main/Amiri-Regular.ttf

أما الدوائر فهذه مشكلة محرك خطوط ميكروسوفت وليس الخط.

**Comment by hatemibrahim1410** [comment]
ألف شكر على الاهتمام،
يعني بشكل عام هذه الخاصية لن تظهر في برامج مايكروسوفت أو الأوفيس ؟؟

هل توجد برامج أخرى غير الأوفيس، تعمل فيها هذه الخاصية ؟؟

**Comment by khaledhosny** [comment]
<div dir="rtl">
أی برنامج لا يستخدم محرك خطوط میكروسوفت، مثل فیرفكس أو كروم أو لیبر أوفیس على وندوز، أو برامج لینكس وماك.

**Comment by hatemibrahim1410** [comment]
تمام، وألف ألف شكر على الاهتمام،

وهناك اقتراح بإضافة 3 خانات للتشكيل:
1- فتحة وكسرة معًا
2- فتحة وضمة معًا
3- ضمة وكسرة معًأ
وبهذا تنتهي هذه الإشكالية في خطوط ميكروسوفت

**Comment by khaledhosny** [comment]
<div dir="rtl">
أين أجد هذا الاقتراح؟

**Comment by hatemibrahim1410** [comment]
هذا اقتراح مني أنا،

في برامج تعديل الخطوط، غالبًا ما تظهر خانات فارغة ليس فيها حروف أو علامات،
فيمكن استغلال هذه الخانات في إضافة هذه الأنواع الثلاثة من التشكيل المزدوج !!

فعلى سبيل المثال،
بجوار الشدة توجد الشدة المضمومة والمفتوحة والمكسورة،
ومن إعداداتها يمكن تبديل الشدة بحركات أخرى !

**Comment by khaledhosny** [comment]
<div dir="rtl">
الخانات الفارغة قد تستخدم فی إصدارات لاحقة من یونیكود لحروف أخرى، كما أن هذا لن یحل المشكلة فی برامج میكروسوفت لأنها إن لم تتعرف على علامة التشكیل ستفصل الحروف العربیة عن بعضها، مثلا بَِ‌يت بدلا بَِيت.

![](https://user-images.githubusercontent.com/93914/93378835-49154880-f85d-11ea-9907-f19bc6a4c434.png)

**Comment by hatemibrahim1410** [comment]
أظنه يمكن إضافة خانات، ولا تكون معتمدة (يونيكود)ـ 
 وأما مشكلة انفصال الحروف ألا يمكن تجاوزها بالإعدادت الموجودة مسبقًا في خانة الشدة المكسورة والمضمومة والمفتوحة ؟!!ـ

**Comment by hatemibrahim1410** [comment]
[معدل.zip](https://github.com/alif-type/amiri/files/5234557/default.zip)
قمت بتعديل بدائي في خانات بجوار صلى الله عليه وسلم
والفكرة نججت نوعًا ما، لكن بإضافة كشيدة قبل أو بعد الرموز
وكذلك ظهرت لي المشكلة التي أشرت إليها بانفصال الحرف، لكن الكشيدة عالجت المشكلة !!

**Comment by hatemibrahim1410** [comment]
هذه نماذج
![Screenshot_3](https://user-images.githubusercontent.com/71362757/93383873-8af5bd00-f864-11ea-91e1-a7abf69be385.png)

وأتصور إن باشرت بنفسك الاقتراح، ستأتي بنتائح أكثر كفاءة من هذا بكثير
