### ISSUE TITLE
ألكشيدة الآلية - justify

### ISSUE THREAD

**Issue by hatemibrahim1410** [aliftype/amiri#201]
السلام عليكم،

في برناج الأوفيس عند استعمال الكشيدة الآلية،
تتم تسوية الأسطر بإضافة مسافات فقط في الخط الأميري،
بينما في خطوط أخرى رسمية وغير رسمية تتم التسوية بإضافة كشيدة 

فهل يمكن إصلاح هذه الخاصية ؟؟
![Screenshot_1](https://user-images.githubusercontent.com/71362757/93704981-b05f2100-fb19-11ea-8e8b-90241db6fa26.png)

**Comment by khaledhosny** [comment]
<div dir="rtl">
الكشيدة الآلیة تفسد اتصالات الحروف فی الخط الأمیری. لو تركت الكشیدة الآلیة مفعلة لظهر هذا النص قریبا من هذه الصورة:

<img width="988" alt="image" src="https://user-images.githubusercontent.com/93914/93710835-c684d580-fb49-11ea-80bd-62ea7b6369cb.png">

**Comment by hatemibrahim1410** [comment]
تمام،
الكن لعل حضرتك تلحظ أن كلمات: [أنا - شاعر - من - شيطانه]؛ النتائج فيها مقبولة جدًا
فإن أمكن العمل على تحسين هذه الخصية مع بقيت الحروف التي يظهر معها تشوه في أول وآخر الكشيدة،
فهذه خاصية مهمة، وجمالية أيضًا.

**Comment by hatemibrahim1410** [comment]
مع لفت الانتباه إلى كون تطبيق الكشيدة بصورة يدوية لا تظهر معها تشوهات واضحة !!
وهذه نماذج يدوية
![Screenshot_1](https://user-images.githubusercontent.com/71362757/93738966-73f9f680-fbe7-11ea-8917-af8d0dddfcee.png)

**Comment by hatemibrahim1410** [comment]
أو كحل ضعيف، يمكن إضافة هذه الكشيدة الآلية إلى الخصائص الاختيارية للأوبن تايب،
ويمكن للمستخدم معالجة التشوهات الشديدة يدويًا !!

**Comment by khaledhosny** [comment]
<div dir="rtl">
الكشیدة الآلیة يضعها البرنامج بعد تنفیذ قواعد أوبن تیب فی الخط، ولا تحكم للخط فیها بأی صورة كانت، ولا یستطیع الخط حتى أن یكتشف إدراج هذه الكشیدة الآلیة من عدمه.
