### ISSUE TITLE
تعديلات (أوبن تايب)ـ

### ISSUE THREAD

**Issue by hatemibrahim1410** [aliftype/amiri#202]
السلام عليكم،

في ملف البي دي أف الملحق بالخط،
قمت ببيان أنه يمكن تعديل بعض الخصائص في الخط من خلال برامج (أوبن تايب)ـ

فهل بالإمكان عرض توضيحي لكيفية اختيار هذه الخصائص ؟؟

**Comment by khaledhosny** [comment]
<div dir="rtl">
تعتمد على البرنامج الذی تستخدمه، مايكروسوفت أوفيس له طریقة مختلفة عن لیبر أوفیس، ومتصفحات الوب تختلف، وبرامج أبل تختلف، وبرامج أدوبی تختلف. لا یسع المجال لذكر هذا كله. یمكنك أن تبحث فی الإنترنت عن طريقة تفعیل خصائص أوبن تیب (OpenType features) للبرنامج الذی تستخدمه.

**Comment by hatemibrahim1410** [comment]
أنا وجدت في برنامج 
font creator 
مجال لتفعيل الخصائص،
لكن قمت بتفعيل الخاصة 
ss02
المخصص للميم المتوسطة التي بعدها ألف، وعند التطبيق في (مايكروسوفت أوفيس) لم تظهر !!ـ

**Comment by khaledhosny** [comment]
<div dir="rtl">
لا تحتاج إلى تعدیل أی شیء فی الخط، فی فونت كریوتر أو غیره، إذا كان البرنامج الذی تستخدمه یدعم خصائص أوبن تیب فهناك قائمة أو أی طریقة أخری لتفعیلها.

**Comment by khaledhosny** [comment]
https://medialoot.com/blog/how-to-enable-opentype-features-in-word-photoshop-and-illustrator/
