### ISSUE TITLE
U+06E0 seems to show as English Zero but it should look like an arabic zero i.e rectangular dot

### ISSUE THREAD

**Issue by fawazahmed0** [aliftype/amiri#203]
Hi,

Thanks for your fonts
The U+06E0 is only used in quran at few specific places, but looks like 0

Amiri Quran Font:
![-2020-oct-5-006](https://user-images.githubusercontent.com/20347013/95103181-f0491980-0751-11eb-9535-f6c52c76eb4e.jpg)

Noto Kufi Arabic Font(shows properly):
![-2020-oct-5-004](https://user-images.githubusercontent.com/20347013/95103236-035be980-0752-11eb-93cd-d06b5e7f6c06.jpg)

Also it would be great if you would fix this issue in your other fonts as well.

This issue was reported by @meezaan at [here](https://github.com/islamic-network/api.alquran.cloud/issues/21#issuecomment-703556434) , you can refer [here](https://github.com/islamic-network/api.alquran.cloud/issues/21#issuecomment-703703724) for more details.

Thanks

**Comment by fawazahmed0** [comment]
Closing this issue based on what @meezaan said at [here](https://github.com/islamic-network/api.alquran.cloud/issues/21#issuecomment-703734931) , it seems to be a mistake in the quran text and U+06E0 should rather be a sukoon

**Comment by fawazahmed0** [comment]
But anyways the english zero thing should still look like arabic zero

**Comment by khaledhosny** [comment]
The shape in Amiri is the correct one, the shape in Noto Kufi Arabic is wrong.

**Comment by khaledhosny** [comment]
Using sukoon is wrong either, it is a different symbol.

**Comment by khaledhosny** [comment]
![IMG_20201005_185300](https://user-images.githubusercontent.com/93914/95108978-40b57c80-073c-11eb-8011-72e6954dcd25.jpg)

**Comment by fawazahmed0** [comment]
@khaledhosny  Thanks, that photo seems to explain everything

**Comment by khaledhosny** [comment]
FWIW, that is taken from Al-Azhar mushaf of 1337 AH (4th print of 1388 AH).

**Comment by fawazahmed0** [comment]
@khaledhosny The [Unicode document](https://www.unicode.org/charts/PDF/U0600.pdf) described U+06E0 as rectangular zero, that's why I assumed it should look like arabic zero, thanks for correcting

**Comment by khaledhosny** [comment]
For completeness sake.

Madina mushaf (1427 AH print):
![IMG_20201005_190215_2](https://user-images.githubusercontent.com/93914/95109829-67c07e00-073d-11eb-8ad1-a066fcc26fe3.jpg)

Al-Shamarly mushaf (1363 AH print):
![IMG_20201005_190029_2](https://user-images.githubusercontent.com/93914/95110409-401de580-073e-11eb-89f6-d3ce10d57106.jpg)

**Comment by khaledhosny** [comment]
> @khaledhosny The [Unicode document](https://www.unicode.org/charts/PDF/U0600.pdf) described U+06E0 as rectangular zero, that's why I assumed it should look like arabic zero, thanks for correcting

Yes, that was a major source of confusing especially that the old Unicode code charts had the wrong glyphs for this and many other Quranic symbols and many fonts blindly copied it.

**Comment by fawazahmed0** [comment]
> 
> 
> > @khaledhosny The [Unicode document](https://www.unicode.org/charts/PDF/U0600.pdf) described U+06E0 as rectangular zero, that's why I assumed it should look like arabic zero, thanks for correcting
> 
> Yes, that was a major source of confusing especially that the old Unicode code charts had the wrong glyphs for this and many other Quranic symbols and many fonts blindly copied it.

I wrote to unicode at [here](https://corp.unicode.org/reporting.html) about the wrong description, otherwise people will start making wrong assumptions like what I did today.

Thanks
