### ISSUE TITLE
Overlapping stop signs

### ISSUE THREAD

**Issue by dscorbett** [aliftype/amiri#204]
In surah 2, ayah 2 of [this Quran](https://archive.org/stream/QuranSindhi/Quran-With-Sindhi#page/n9/mode/1up), there are three consecutive stop signs in ⟨رَیۡب⟩. In Amiri, they overstrike each other.
![رَیۡب](https://user-images.githubusercontent.com/1124347/95787185-fe91bb00-0ca6-11eb-993d-af0ce5e6731c.png)

**Comment by khaledhosny** [comment]
Hmm, Amiri follows a different orthography where such combinations can never happen. I’m not even sure this is the right input, the three dots as spacing and slightly above baseline, not a combining mark. I can not lower the three dots in Amiri, so even if the stacking is fixed it would still be too high to be usable.

**Comment by dscorbett** [comment]
Although the three dots are spacing, I think they should still be encoded as U+06DB ARABIC SMALL HIGH THREE DOTS. In this Quran’s style, it seems that stop signs are often spacing and slightly above the baseline; cf. U+06DA ARABIC SMALL HIGH JEEM in ayah 4, U+08D7 ARABIC SMALL HIGH QAF in ayah 5, and another stack of <U+06DA, U+06D6> in ayah 14.

I understand if you decline to support this, but I only just discovered this and I thought it was too interesting not to report.

**Comment by khaledhosny** [comment]
It is interesting indeed, but as you pointed out this orthography (the Indian subcontinental one) is too different to be supported by Amiri at the same time unless these marks have different code points (short of making a dedicated font for this orthography).

CC’ing @roozbehp in case he has some insight on this.
