### ISSUE TITLE
Add Unicode Reverse Comma and Semicolon

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [aliftype/amiri#207]
In last year, SIL announced they have added alternative feature to Arabic comma and semicolon in the Scheherazade New font, which is available while you specify Sindhi as locale language, just like what you have made in #145. But the [web demo](https://software.sil.org/scheherazade/support/smart-font-features/) also claimed:
> Unfortunately, the UI needed to access the language-specific behavior is not yet present in many applications. LibreOffice and Microsoft Word 2016 support language-specific behavior for Kurdish, Sindhi and Urdu (but not Kyrgyz, Rohingya or Wolof). Some Harfbuzz-based apps, e.g., XeTeX, can access language-specific behavior.

But I found Unicode provides two characters can be used to present on MS Word: U+2E41 and U+204F. As a work around, you can add this characters in Amiri font.

**Comment by khaledhosny** [comment]
Already done in aae5aa9a0e718c8613b320055a1a30f18cb25ae7
