### ISSUE TITLE
Add alternate glyph for Heh Goal

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [aliftype/amiri#210]
After #123, I think it’s possible to create a font feature for Heh Goal, which could produce a variant that has additional stroke at the bottom.

**Comment by khaledhosny** [comment]
Please elaborate a bit.

**Comment by KrasnayaPloshchad** [comment]
OK, let me explain. This letter usually performed as this:
![图片](https://user-images.githubusercontent.com/10364351/106363848-01074600-6366-11eb-842f-44c74382e565.png)
After the above issue, you can get a spline from U+06C7, then you can create a variant for Heh Goal as initial form, which could be looks like this:
![图片](https://user-images.githubusercontent.com/10364351/106363928-7d018e00-6366-11eb-9752-812f9256e6d1.png)
Then you can make it available as alternate feature.

**Comment by moyogo** [comment]
@KrasnayaPloshchad that doesn’t explain why this should happen.

See https://twitter.com/OmarTypeFoundry/status/785064854642130946 or http://omar-type.com/Muhammad/Initial%20shaping%20rules%20for%20Unicode%2006C1.pdf for why this is sometimes not recommended in Naskh.

**Comment by moyogo** [comment]
I misunderstood. If this is an alternate, I guess there's less reasons not to.

**Comment by KrasnayaPloshchad** [comment]
> If this is an alternate, I guess there's less reasons not to.

Yes.

**Comment by KrasnayaPloshchad** [comment]
@moyogo So what about SIL’s design for this letter?
