### ISSUE TITLE
Fix Gaf variant

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [aliftype/amiri#214]
It looks weird that the Gaf variant still have ascender in the isolated form.
![图片](https://user-images.githubusercontent.com/10364351/106364444-fe0e5480-6369-11eb-8616-a928e926fb18.png)

**Comment by khaledhosny** [comment]
I‘m not sure if I understand the issue. If you mean the serif-like part, that is a property of this form kaf and can’t be removed.
