### ISSUE TITLE
Support Persian characters

### ISSUE THREAD

**Issue by xmha97** [aliftype/amiri#215]
Please support Persian characters for `Amiri Quran` and `Amiri Quran Colored`:
![image](https://user-images.githubusercontent.com/23485114/108366935-2c1ae200-720e-11eb-8084-bb5e7caf13db.png)
Missing characters: `گ` `ک` `پ` `چ` `ژ`

**Comment by khaledhosny** [comment]
Amiri Quran is a subset of Amiri that supported only characters used in Quranic Arabic text, for general uses regular Amiri font is preferred.
