### ISSUE TITLE
خَطَأٌ فِي عَلَامَةِ التَنْصِيْصِ

### ISSUE THREAD

**Issue by hsanmazn** [aliftype/amiri#218]
<div dir="rtl">
تظهر علامة التنصيص أول الضغط عليها هكذا ” " “، فإذا أضفنا إليها أخرى كتبت هكذا ” "” “، وعند كتابة الثالثة بعد مسافة تصبح ” "” “ “.

وأنا – وأعوذ بالله من كلمة أنا – أقترح أن تظهر علامة التنصيص عند كتابتها بعد أي مسافة هكذا ” ” “، ثم إذا وضعت في ظهر أي حرف مباشرة دون مسافة قبلها تكتب هكذا ” “ “، وبهذه الطريقة تأخذ العلامة شكلها الطبيعي أثناء الكتابة دون تدخل من الكاتب، مع الإبقاء على إمكانية كتابتها على الشكلين في أي موضع بجعل ظهورها بالتناوب؛ أي إذا كتبت علامة تنصيص ثالثة في ظهر الثانية تظهر كما الأولى هكذا ” ”“” “، وتأتي التي بعدها عكسها، وهكذا بأي عدد كتبت…

ونسأل الله لنا ولكم التوفيق والسداد!
[مراجعة خطأ التنصيص في الخط الأميري.pdf](https://github.com/alif-type/amiri/files/6371902/default.pdf)

**Comment by khaledhosny** [comment]
<div dir="rtl">
هذا خطأ من التطبیق الذی تستخدمه لتحریر النص، فهذا الاستبدال لعلامات التنصیص لا تدخل للخط فیه.
