### ISSUE TITLE
Can't keep slanted style in pdf exports

### ISSUE THREAD

**Issue by boglethemogle** [aliftype/amiri#219]
Please excuse me if this question has an obvious answer or anything like that. I don't know much about fonts, and am a complete novice here.

I used the English variation of this font in a document I created in Affinity Publisher. Everything looked good on Publisher, but when I export it to pdf, all the slanted fonts come out looking like the regular style. Is there anything I can do to correct this?

**Comment by khaledhosny** [comment]
That sounds like a bug in Affinity Publisher.

**Comment by boglethemogle** [comment]
Yeah, I tried it with LibreOffice, and was able to get slanted text exported to pdf no problem. Definitely an Affinity problem. Thanks for your help, and sorry for the bother. 

Also, it's an absolutely beautiful font.

**Comment by khaledhosny** [comment]
Thank you, though the credits for the Latin part goes to https://github.com/skosch/Crimson.
