### ISSUE TITLE
Rounded "2"

### ISSUE THREAD

**Issue by gounaman** [aliftype/amiri#220]
I've started developing an Arabic Calculator SPA, which I am moving to GitHub shortly. It uses the Amiri font.

Early beta can be found here.

https://codepen.io/zette/pen/OJpvdVr

My question is:

Is it possible for someone to add a numeral "2" with a rounded "hood" or top to reflect how this number is handwritten in Egypt?

Maybe this could be added to the typewriter version?

Many thanks.

**Comment by khaledhosny** [comment]
It should be possible as an alternate glyph, but I can’t make any estimates on when this would be done.

**Comment by gounaman** [comment]
No worries. I still have to write the algorithm/api that enables JavaScript to arithmetically process Arabic glyphs as number data types. Please let me know if this request/enhancement ever becomes a real possibility, instead of a permanent "fil mish mish one." ;-)
