### ISSUE TITLE
Unicode Character “٬” (U+066C) is upside down?

### ISSUE THREAD

**Issue by gounaman** [aliftype/amiri#221]
This character in the Amiri typeface appears to be displaying incorrectly.  I am using an Intl.NumberFormat('ar-EG') JS object to process Arabic numerals in my application, running under Windows 10 with the latest Edge/FF/Chrome browsers.  The JS object inserts the formatted glyph automatically from "Western Arabic" numeric input. It works fine for other characters, but the thousands separator unfortunately appears upside down. This also happens with the Google Lateef typeface, but not, strangely enough, the Cairo one.  As it now stands, I'm going to use Cairo going forward until there is a fix or resolution.

![Ameer vs Cairo fonts](https://user-images.githubusercontent.com/44690477/122327969-c52be200-cefc-11eb-8298-0a6b3fe624b2.png)

**Comment by khaledhosny** [comment]
That is how this symbol looks like in Amiryia press prints, the one you have on the right looks like the decimal separator and would be rather confusing. Anyway, thousands separators are rarely used in Arabic (if at all these days), and JS API is probably wrong in using it.

**Comment by khaledhosny** [comment]
Duplicate of #179

**Comment by gounaman** [comment]
thank you for your kind reply.
i have asked a contact in Cairo to obtain and send me an official current Egyptian textbooks in Arabic that shows placement of thousands separator as well as correct placement of minus signs.
if JavaScript's international format ar-EG implementation is wrong, then I will raise the issue with the W3C.
I show all this clearly in a working demo on CodePen:

https://codepen.io/zette/pen/WNpPWXm

as you can see, I am using the correct thousands separator, vs the decimal sign which has a different Unicode identifier.

btw, my first name is Ali. this "zouzette" handle is just for privacy reason on proton mail.

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
