### ISSUE TITLE
الكشيدة لا تعمل في انديزاين أدوبي

### ISSUE THREAD

**Issue by Ahmee8** [aliftype/amiri#223]
![image](https://user-images.githubusercontent.com/89326378/130339351-ec7241d3-49db-4628-82a6-7fa4f7a3ad40.png)
![image](https://user-images.githubusercontent.com/89326378/130339375-c84176a2-5fb1-4541-a88d-8ee84f7f1b7c.png)
![image](https://user-images.githubusercontent.com/89326378/130339387-20e9c3ca-bf7b-4bcd-a74b-fbcd55e4fca4.png)

السلام عليكم. في البدء، كل الشكر لجهدك المبذول في إثراء مكتبتنا العربية. من القلب أدعو لك.
في الصور أعلاه، تظهر مشكلتي مع الكشيدة في ادوبي اندزاين. علمًا أن الكشيدة تعمل مع خطوط اخرى في نفس البرنامج، مثل خط لوتس.
أرجو توجيهي إن كان هناك خطأ. (بحسب الصور، يفترض ان الاوبن تايب مفعل، فليست المشكلة في تفعيله، إن كنت مخطئ فأرجو توضيح ذلك)

مع التحية، أحمد

**Comment by khaledhosny** [comment]
للأسف الكشیدة الآلیة التی تضيفها البرامج غیر متوافقة مع الخط الأمیری، لذا یحتال الخط على البرامج لإلغائها.

انظر أیضا https://github.com/aliftype/amiri/issues/201

**Comment by khaledhosny** [comment]
Duplicate of #201
