### ISSUE TITLE
المسافة كبيرة بين الكاف والراء

### ISSUE THREAD

**Issue by hichochar** [aliftype/amiri#224]
الرجاء تقصير المسافة بين الكاف والراء لأن كاف بعيدة لدرجة انها تبدو كلمة منفصلة

**Comment by Abdullah16M** [comment]
الكاف حين تأتي قبل الراء، أو بعدها؟ متصلة أو منفصلة؟ وضح

.أعتقد أنك تقصد الراء قبل الكاف في حالة أن الراء لم تكن متصلة بشيء قبلها، مثلًا: ركل، ركم، ركس، ..إلخ، وفي هذه الحالة فالراء حقٌ بعيدة عن الكاف

.وهذا نفس الحال مع الواو قبل الكاف غير متصلة، مثلًأ: وكل، وكر، ..إلخ
