### ISSUE TITLE
سؤال عن (U + 0601) و (U + 0600).

### ISSUE THREAD

**Issue by IlyasTarpan** [aliftype/amiri#243]
السلام عليكم!
يمكن أن تحتوي الأحرف (U + 0601) و (U + 0600) على أربعة أرقام فقط كحد أقصى. هذا صحيح؟ لماذا لا تجعل من الممكن وضع عدد غير محدود من الأرقام؟
إذا لم يكن هذا خطأ ، فأنا آسف
![Снимок экрана (14)](https://user-images.githubusercontent.com/113206717/196908771-a0a9b807-19a8-45f0-8be8-dbb9cce2b37e.png)

**Comment by khaledhosny** [comment]
> السلام عليكم! يمكن أن تحتوي الأحرف (U + 0601) و (U + 0600) على أربعة أرقام فقط كحد أقصى. هذا صحيح؟ 

نعم

> لماذا لا تجعل من الممكن وضع عدد غير محدود من الأرقام؟ إذا لم يكن هذا خطأ ، فأنا آسف 

في حالة علامة السنة لأنه يلزمنا حوالي ٨٠٠٠ قبل أن نحتاج لرقم خامس في السنة الميلادية (وأكثر قليلا للسنة الهجرية). في حالة علامة العد لأن كل رقم إضافي يحتاج رسم نسخة أكبر من العلامة ولم يطلب هذا أحد من قبل، فإن كان عندك احتياج حقيقي لخمسة أرقام يمكن أن أفكر في الأمر.

**Comment by IlyasTarpan** [comment]
آسف لعدم الرد.
أوافق على رمز التاريخ (؁) ، فهو لا يحتاج إلى الإصلاح ، على الرغم من أن بعض الخطوط ، مثل Segoe UI ، سمحت لك بوضع عدد غير محدود من الأرقام عليه.
    على سبيل المثال ، يقصرون علامة الرقم الفرعي (؀) على أربعة أرقام ، على الرغم من أن هذا ليس صحيحًا تمامًا من الناحية النظرية. الكل في الكل ، إنه نوع من الغموض.
    أعتقد أنه لا يوجد شيء لإصلاحه ، لقد اعتقدت أن الحد الأقصى لعدد الأحرف البالغ 4 كان خطأً ، لكن اتضح أنه كان موجودًا في جميع الخطوط.
    ؁١٢٣٤٥٦٧٨
    ؀١٢٣٤٥٦

**Comment by IlyasTarpan** [comment]
![Снимок экрана (15)](https://user-images.githubusercontent.com/113206717/197520308-7aa302d4-cdfc-4f48-a83c-01dce3d5b741.png)

**Comment by khaledhosny** [comment]
شكل العلامة في Segoe UI يسمح بإطالتها بسهولة، لكن شكلها في الأميري لا يسمح بهذا.

**Comment by IlyasTarpan** [comment]
حسنًا ، أعتقد أنه يمكننا إغلاق السؤال. شكرًا لك!
