### ISSUE TITLE
Request to improve tatweel                                                                                                      طلب تحسين تطوير

### ISSUE THREAD

**Issue by IlyasTarpan** [aliftype/amiri#246]
Big greetings!
Firstly, I want to thank you for such a beautiful font. Amiri is the most beautiful Naskh font (and probably one of the 2) that has such wide character support and can be used for my native language, Crimean Tatar.
Secondly, I want to apologize if my request has already been duplicated somewhere.
Thirdly, I want to gain forgiveness for writing in English and not in Arabic. Unfortunately, the translation from Russian into Arabic is rather crooked :(. Maybe someday I will know Arabic better and will communicate in it.

I would like to ask you to make tatweel in Amiri more... calligraphic :).
I will give you an example of how four words were written in a Turkish atlas, around 1920 (كیتره ,توركیه ,آنقره ,روسیه).
![photo_2022-12-05_14-51-53](https://user-images.githubusercontent.com/113206717/205641889-e0e6b9d1-ce32-4b20-a37a-c4444918bc05.jpg)
![photo_2022-12-05_14-52-03](https://user-images.githubusercontent.com/113206717/205641894-8eec4988-d574-4e24-be35-8d1335ab06f9.jpg)
![photo_2022-12-05_14-52-01](https://user-images.githubusercontent.com/113206717/205641896-e02ae0ce-d606-4ec5-8a54-69a55a777f4b.jpg)
![photo_2022-12-05_14-52-00](https://user-images.githubusercontent.com/113206717/205641898-26d34d12-bdd1-40eb-bf59-b1985d16169d.jpg)
As you can see, when tatweel is used in these words, it sort of "sags" down.
  In Amiri, tatweels, although they have a bend, but very small. And if you score more than 7 tatweels in a row, then they become completely straight, which does not look very nice.
![photo_2022-12-05_13-52-40](https://user-images.githubusercontent.com/113206717/205642043-ec45cc43-88c1-47f5-a6b6-76bad8f479ae.jpg)
![photo_2022-12-05_13-52-37](https://user-images.githubusercontent.com/113206717/205642046-17f1dd81-8e21-4e9b-a160-b329f321eb6f.jpg)
![photo_2022-12-05_13-52-33](https://user-images.githubusercontent.com/113206717/205642048-08def012-2469-4720-b2c0-03131d7d9114.jpg)
![photo_2022-12-05_13-52-27](https://user-images.githubusercontent.com/113206717/205642050-0cdfec81-b668-43c9-900f-bfe2d3e1da6c.jpg)
![photo_2022-12-05_13-52-38 (2)](https://user-images.githubusercontent.com/113206717/205642279-45e131de-b72c-4e50-8634-da902f6cc9fe.jpg)

 In my opinion, tatveels are best designed in Aldhabi font. Tatweels have a more natural shape there, and 10 tatweels can be cast in a row without losing shape. Also, for example, dots ي are moved to the middle.
![photo_2022-12-05_13-52-30](https://user-images.githubusercontent.com/113206717/205642192-980df754-05a9-40a4-872c-e7f82533f418.jpg)
![photo_2022-12-05_13-52-29](https://user-images.githubusercontent.com/113206717/205642197-f40e1bf4-3d9b-458a-b7c5-7c1c1a034c95.jpg)
![photo_2022-12-05_13-52-42](https://user-images.githubusercontent.com/113206717/205642199-79bfdfc9-3888-4d7b-82b0-7467ddb2fec6.jpg)
![photo_2022-12-05_13-52-39](https://user-images.githubusercontent.com/113206717/205642202-e561707d-2df7-467c-9867-a60e7e78dfee.jpg)
![photo_2022-12-05_13-52-38](https://user-images.githubusercontent.com/113206717/205642206-a3a4c6a0-f882-4214-b5fe-93bbfd2a73a3.jpg)
  Even though Aldkhabi is Diwani style and Amiri is Naskh, could you make a similar form of tatweel in Amiri considering that it was used? To make the tatweel more curved, more alive.
  Perhaps you will say that Amiri is primarily a computerized typographic font, not a calligraphic one, and therefore the tatweels there are straight. But for example, the glyph of Basmala ﷽  is written with a beautiful curve of the tatweel, and it looks very beautiful. 
It seems to me that a similar bend is better done with a regular glyph (U+0640) as well.

مع أطيب التحيات إلياس تارپان
Best regards, Ilyas Tarpan

**Comment by khaledhosny** [comment]
I’m aware of the calligraphic requirements of tatweel and the current limitations of Amiri. Unfortunately fixing this properly in Amiri would require a considerable effort.

I have frozen the development of Amiri because at its current state any further development will require disproportionate effort. I might start working on a newer version that would be re-built in a way that allows addressing many of Amiri’s current limitations and I would then consider issues like this, but I can commit to any specific time frame right now.
