### ISSUE TITLE
Add Arabic honorifics

### ISSUE THREAD

**Issue by amarakon** [aliftype/amiri#252]
From the [kitab-font](https://github.com/quranacademy/kitab-font) repository I read:

> The following honorifics were added (note: these honorifics are set to be included in Unicode 14)
>
> - U+FDFE (سبحانه وتعالى)
> - U+FDFF (عز وجل)
> - U+FD40 (رحمه الله)
> - U+FD41 (رضي الله عنه)
> - U+FD42 (رضي الله عنها)
> - U+FD43 (رضي الله عنهم)
> - U+FD44 (رضي الله عنهما)
> - U+FD45 (رضي الله عنهن)
> - U+FD47 (عليه السلام)
> - U+FD4D (عليها السلام)
> - U+FD48 (عليهم السلام)
> - U+FD49 (عليهما السلام)

Can you add these honorifics to Amiri?

**Comment by khaledhosny** [comment]
Amiri is frozen and now further development is planned. These symbols are also complex and would require a lot of work to draw. I suggest you use a different font for these symbols, e.g. [Kitab](https://github.com/quranacademy/kitab-font/).
