### ISSUE TITLE
دمج  الخط القرآني في الخط الرئيسي كخاصية Stylistic Set

### ISSUE THREAD

**Issue by hubaishan** [aliftype/amiri#257]
الخط الأميري  محمل على خطوط جوجل، وكذلك على ويكيبيديا ، لكن الخط القرآني ليس محملًا عليهما فإذا دمج الخط القرآني في الخط الأميري كخاصية اختيارية (Stylistic Set) فإن هذا سيوفر لنا عرض نص قرآني متكامل على مواقع أجنبية المنشإ تدعم الخط الأميري، كذلك سيوفر في حجم تحميل صفحات الويب، في المواقع الخاصة التي تستضيف الخط الأميري على سيرفراتها، بقي ارتفاع الخط يمكن التحكم به من خصائص css.

**Comment by khaledhosny** [comment]
الخط العادي يدعم كل ما يدعمه الخط القرآني، الاختلاف الوحيد هو حجم علامات التشكيل في الخط القرآني ولا أظنه يعوق استخدام الخط العادي مع النصوص القرآنية.

**Comment by hubaishan** [comment]
وهمزة على ياء وعلى واو (ئ، ؤ) المكسورتان في القرآني تتموضع الهمزة في الأسفل، والياء المتطرفة في القرآني لا تنقط

**Comment by khaledhosny** [comment]
> وهمزة على ياء وعلى واو (ئ، ؤ) المكسورتان في القرآني تتموضع الهمزة في الأسفل، والياء المتطرفة في القرآني لا تنقط

في رأيي، أن الهمزة في هذه الحالة يستخدم لها رمز الهمزة السفلية، والياء يستخدم لها ما تسميه يونيكود خطأ ياء فارسية. هذا يضمن أن يظهر النص القرآني بالتنسيق المطلوب بغض النظر عن الخط أو البيئة المستخدمة.
