### ISSUE TITLE
 مشكلة في تموضع ألف مد القصيرة وعلامة من علامات التشكيل قرآني في حرف الجر إلى

### ISSUE THREAD

**Issue by Mos6720009** [aliftype/amiri#258]
عندما كنت اكتب بالخط الأميري العادي ليس القرآني كتبت آية بها إلى فوجدت تموضع ألف المد القصيرة وعلامة من علامات التشكيل القراني فكان شكلها غير شكلها في المصحف الأميري
شكلها في الخط 
![لقطة الشاشة 2023-05-27 184527](https://github.com/aliftype/amiri/assets/112905893/ebf3a144-0930-4a58-b1ae-29cf92274d71)
شكلها في المصحف الأميري
![لقطة الشاشة 2023-05-27 185158](https://github.com/aliftype/amiri/assets/112905893/c0c99a3a-3828-4c57-901e-f6b69c78df2d)

**Comment by khaledhosny** [comment]
للمدة القرآنية استخدم علامة [U+06E4](https://en.wiktionary.org/wiki/%DB%A4) وليس U+0653.

أما موضع الألف فكلاهما مقبول.
