### ISSUE TITLE
اضافة رموز

### ISSUE THREAD

**Issue by AboAliElwahy** [aliftype/amiri#261]
جزاكم الله خيرا على الحط
عندي اقتراح 
انا استخدم الخط amiri في برنامجي ولكني بحاجة لاضافة بعض الرموز للخط مثل رحمه الله ورضي الله عنهم ورضي الله عنه وتبارك وتعالى

**Comment by khaledhosny** [comment]
تطوير خط أميري اكتمل ولا نية لإضافة أي رموز جديدة إليه.
