### ISSUE TITLE
التشكيل قبل حرف الكاف يتسبب بمسافة غير ضرورية

### ISSUE THREAD

**Issue by MoamenAbdelsattar** [aliftype/amiri#274]
هكذا تبدو كلمة "ممدكم" قبل تشكيل الدال:
![image](https://github.com/user-attachments/assets/fe3c9dca-40f0-4ecd-9321-e8a07d34366a)
وهكذا تبدو بعد تشكيل الدال:
![image](https://github.com/user-attachments/assets/0434ffa3-f16d-4344-aa43-48619d05db5f)
وهكذا هو الشكل الصحيح في المصحف:
![image](https://github.com/user-attachments/assets/6b3e033e-4703-4df2-9f34-aa14e1f4383d)

لاحظت نفس التأثير عند تشكيل د أو ذ أو ر أو ز أو و أو ا قبل أي كاف، مثلا:
![image](https://github.com/user-attachments/assets/84f0e3fd-bb8e-4059-9a88-4f92c8ab1913)
والصحيح:
![image](https://github.com/user-attachments/assets/2bb35915-30cb-4e57-b3c2-d3ddb765bd01)

**Comment by khaledhosny** [comment]
This one of the limitations of Amiri’s design. Fixing this requires a substantiation amount of work, not to mention that the project is frozen and a change like this will cause text reflow.
