### ISSUE TITLE
مشكلة في تموضع الحركات

### ISSUE THREAD

**Issue by khaledhosny** [aliftype/amiri#47]
انظر الاشكال المرفقة
![amiri-test2](https://cloud.githubusercontent.com/assets/93914/9018119/15a9c29c-37dc-11e5-80df-736ff0115778.png)
![amiri-test3](https://cloud.githubusercontent.com/assets/93914/9018121/19477ed0-37dc-11e5-956d-7b0d44b9fb9c.png)
![amiri-test4](https://cloud.githubusercontent.com/assets/93914/9018127/1e55689c-37dc-11e5-9715-a5388649f560.png)
![amiri-test6](https://cloud.githubusercontent.com/assets/93914/9018130/225fe6c4-37dc-11e5-80a5-2af662531a1f.png)
![amiri-test7](https://cloud.githubusercontent.com/assets/93914/9018132/2887bfc2-37dc-11e5-885d-51883b6fe960.png)
![amiri-test8](https://cloud.githubusercontent.com/assets/93914/9018134/2c0a16ae-37dc-11e5-83b9-f5bca009cf65.png)

Original comment by: fedoraman

**Comment by SafaAlfulaij** [comment]
![الخَوّانة](https://cloud.githubusercontent.com/assets/3509617/10225977/d6b1f36c-686d-11e5-88c5-e9fea2587397.png)
![الجَأْش](https://cloud.githubusercontent.com/assets/3509617/10225978/d6b84424-686d-11e5-9933-8134a8f078d3.png)

علل في كلمات أخرى

**Comment by SafaAlfulaij** [comment]
<p dir="rtl">
وأخرى (النسخة القرآنية بها نفس العلل أيضا)
</p>

![screenshot_ _](https://cloud.githubusercontent.com/assets/3509617/11295116/154d07c8-8f7a-11e5-9965-d5e8cac6b678.png)
![screenshot_ _](https://cloud.githubusercontent.com/assets/3509617/11295117/155254e4-8f7a-11e5-9db0-2bf7b20fe689.png)
![screenshot_ _](https://cloud.githubusercontent.com/assets/3509617/11295118/1553c626-8f7a-11e5-8adc-d44b9f257423.png)
![screenshot_ _](https://cloud.githubusercontent.com/assets/3509617/11295119/1559bfb8-8f7a-11e5-959e-a53236eb0206.png)
![screenshot_ _](https://cloud.githubusercontent.com/assets/3509617/11295126/1616cb8a-8f7a-11e5-8fc0-1dfff38c6cf8.png)
![screenshot_ _](https://cloud.githubusercontent.com/assets/3509617/11295124/15ac3fe0-8f7a-11e5-83c8-51e4e7b0af33.png)
![screenshot_ _](https://cloud.githubusercontent.com/assets/3509617/11295121/159b6274-8f7a-11e5-9afe-f6ec697117b4.png)
![screenshot_ _](https://cloud.githubusercontent.com/assets/3509617/11295122/15a60710-8f7a-11e5-90f7-597aca766e52.png)
![screenshot_ _](https://cloud.githubusercontent.com/assets/3509617/11295123/15a898e0-8f7a-11e5-9fba-bf469a794901.png)
![screenshot_ _](https://cloud.githubusercontent.com/assets/3509617/11295125/15ae6d42-8f7a-11e5-98c1-8ab82953ee51.png)
