### ISSUE TITLE
The End of Ayah

### ISSUE THREAD

**Issue by khaledhosny** [aliftype/amiri#54]
يسرني جدا ظهور الإصدار الجديد من الخط الأميري 0.102 و أنا استخدمته منذ الإصدار القديم 0.101 لعرض الأحرف الهجائية في مدونتي.
و لكن مع الأسف وجدت مشكلة جديدة فى الإصدار الجديد لم أجدها فى الإصدار القديم. عندما جربت كتابة رقم الأية فى علامة the end of ayah (U+06DD) و رقم الأية عشرة فما فوقها فالرقم لا تظهر صحيحا.
عفوا و جزاكم الله خيرا و أرجو الإصلاح فى الإصدار القادم.

Original comment by: msrosyidi

Original Ticket: [amiri/bugs/59](https://sourceforge.net/p/amiri/bugs/59)

**Comment by khaledhosny** [comment]
The end of ayah using Amiri 0.101 in Microsoft Word

Original comment by: msrosyidi

**Comment by khaledhosny** [comment]
The end of ayah using Amiri 0.102 in Microsoft Word

Original comment by: msrosyidi

**Comment by khaledhosny** [comment]
شكرا على الملاحظة، وآسف على عدم اكتشاف الأمر مبكرا. أضفت اختبارا إلى حزمة الاختبار كيلا يتكرر هذا الخطأ مرة أخرى. سأرفق نسخة مصححة من الخط لتجربها.

Original comment by: khaledhosny

**Comment by khaledhosny** [comment]
Fixed font

Original comment by: khaledhosny

**Comment by khaledhosny** [comment]
This issue has been fixed in the latest release.

Original comment by: khaledhosny

**Comment by adiramardiani** [comment]
Is it possible to enter the _**number**_ at/inside _**End of Ayah**_ symbol ?

**Comment by khaledhosny** [comment]
Of course it is.

**Comment by adiramardiani** [comment]
Please, how to do it ?

Thanks

**Comment by khaledhosny** [comment]
If you enter the end of ayah symbol followed by the numbers (with no spaces in between), it should just work. If this does not work, then it might be a software bug, so please tell me what application/operation system you are trying this on.

**Comment by adiramardiani** [comment]
I use webfont (from google font) and try to show in html file
I can't understand what's your mean in :

> enter the end of ayah symbol followed by the numbers (with no spaces in between)

something like `&#1757;1`
or `1&#1757;`
or `1&#1757;1`
it's not working

for example I use :
بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ ۝
with `&#1757;` HTML Entity (decimal)
and i want to give number in end of ayah

Thanks for helping me and sorry for my stupid question :)

**Comment by khaledhosny** [comment]
Can you show a screenshot? Google Fonts subsets the fonts by default, so I think you might not be getting the end of ayah simple from Amiri font but just a fallback. You will probably need to define your own subset and pass it using the `text=` parameter (consult Google Fonts API documentation for the details).

**Comment by adiramardiani** [comment]
I don't know whats the `Google Fonts subsets`
But after i use web font from this [relase ](https://github.com/khaledhosny/amiri-font/releases/tag/0.108), it's work
![untitled-1](https://cloud.githubusercontent.com/assets/8703419/18622184/34ac30f0-7e56-11e6-8feb-10675cd525f4.png)

Thank you so much for your help
I write unicode U+06DD in html is with html entity symbol
`U+06DD` = `&#1757;`

I write `&#1757;1` to show 
![untitled-1](https://cloud.githubusercontent.com/assets/8703419/18622220/a8d598b8-7e56-11e6-9650-efbd167091f2.png)

Btw, sorry out of topic, the latest release is 0.108 in 21 Sep 2015, and this revo has update 29 days ago
- Is there a latest(newest) release of this font (after 0.108) ?
- How do I compile from this repository to generate web font ?

**Comment by khaledhosny** [comment]
By default Google Fonts provides only a smaller part (subset) of the font covering certain Unicode characters. Their Arabic subset includes only commonly used characters and it does not include end of ayah mark. What I was suggesting is instead of using:

```
https://fonts.googleapis.com/css?family=Amiri&subset=arabic
```

Use something like:

```
https://fonts.googleapis.com/css?family=Amiri&text=%DB%9D
```

(with `%DB%9D` being the end of ayah mark, you also need to specify any other character you need). See https://developers.google.com/fonts/docs/getting_started#optimizing_your_font_requests_beta for more details.

0.108 is the latest release, there no much changes since that release so I don’t think I’m making a new release any time soon. Building from the repository is rather hard to setup, unfortunately.

**Comment by tarekeldeeb** [comment]
After almost 7 years, I think I'm still facing the very same issue.
I should be using the correct font with the extra correct character:
```HTML
<link href="https://fonts.googleapis.com/css?family=Amiri Quran&text=%DB%9D" rel="stylesheet">
<style>
		body {
			font-family: Amiri Quran, serif;
			font-size: 24px;
		}
```
But I get the number our of the Ayah mark as seen:
![image](https://github.com/aliftype/amiri/assets/90985/791f96d4-86b4-4e54-9c3f-0ca066782c2b)

**Comment by khaledhosny** [comment]
What browser/version is this and what OS?

**Comment by tarekeldeeb** [comment]
Windows 10
Chrome Version 113.0.5672.127 (Official Build) (64-bit)

**Comment by khaledhosny** [comment]
Can you attach a small HTML file or URL I can check?

**Comment by tarekeldeeb** [comment]
```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Arabic Sentence in Amiri Font</title>
    <style>
      /* Import the Amiri font from Google Fonts */
      @import url('https://fonts.googleapis.com/css2?family=Amiri Quran&text=%DB%9D');
      
      /* Set the body font to Amiri */
      body {
        font-family: 'Amiri', serif;
      }
    </style>
  </head>
  <body>
    <p>1بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ ۝</p>
  </body>
</html>
```

**Comment by tarekeldeeb** [comment]
Same issue appears on Latest Ubuntu with Chrome 113 as well.

**Comment by khaledhosny** [comment]
Your string starts with the number 1 and ends with the ayah sign, I have no idea why this worked before, but I’m sure it was by accident. I did some cleanup in how ayah handling work and removed a workaround that was no longer needed and probably that what broke this. The ayah sign should be directly followed by the number, i.e.:
```
<p>بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ ۝1</p>
```

**Comment by khaledhosny** [comment]
Left is your string, right is the corrected one:
<img width="624" alt="image" src="https://github.com/aliftype/amiri/assets/93914/a27b355f-f91f-404a-a7eb-b2021ae05b6e">

**Comment by tarekeldeeb** [comment]
You are correct, my example string was wrong. I fixed it as you said, still the issue appears in Chrome and IE as well
![image](https://github.com/aliftype/amiri/assets/90985/021baef3-6362-40bd-965e-4f615adae727)

Regarding your last message (cleanup, possible fix) did you release a new version? I need to test it please at my side.

Thanks in advance

**Comment by khaledhosny** [comment]
Do you intend to use the font from Google Fonts or locally? Because you are importing Amiri Quran but you use Amiri. But even of you used Amiri Quran it will not work as you pass `text=%DB%9D` which will only import the end of ayah sign, but for the numbers to get inside the symbol they have to come from the same font.

**Comment by tarekeldeeb** [comment]
I want to use "Amiri Quran" from google fonts (local/cdn is ok for me as well). I tried to remove the text param and got the same issue. 
![Screenshot from 2023-06-17 05-44-56](https://github.com/aliftype/amiri/assets/90985/17f3aa75-50f3-4db7-8c2f-42b0a9d95632)


I'm really confused: is there a font regression bug or I'm missing the correct practice?

**Comment by khaledhosny** [comment]
AFAIK, the font is working fine. The text in your screenshot still has the same issue as in https://github.com/aliftype/amiri/issues/54#issuecomment-1585679811

**Comment by tarekeldeeb** [comment]
Many thanks Khaled for your time and support. it turned out to be the googleapis version is very old. [This is serving](https://fonts.cdnfonts.com/css/amiri-quran-colored) an updated working version. Do you have an official CDN to use? where the fonts are regularly updated.

**Comment by khaledhosny** [comment]
This is the old version actually. Google Fonts are currently serving the latest version AFAIK.
