### ISSUE TITLE
Support for Indonesian Mushhaf

### ISSUE THREAD

**Issue by khaledhosny** [aliftype/amiri#68]
I want to ask to add some support for writing Quranic Verses according to the Indonesian Mushhaf.
Thanks.

Original comment by: msrosyidi

Original Ticket: [amiri/feature-requests/14](https://sourceforge.net/p/amiri/feature-requests/14)

**Comment by khaledhosny** [comment]
Support for Indonesian Mushhaf

Original comment by: msrosyidi

**Comment by khaledhosny** [comment]
Sorry Muhammad for the long delay.

-2, A: should be written as “تَأۡمَـ۫نَّا” i.e. with a tatweek after the meem holding the second mark because it does not belong to either letter, but is placed between them.

-2, B: first one is fixed, I’m not yet sure how to handle the inverted damma properly for both Urdu and Indonesian.

-3, A: all seem like software not font issues, please test with Firefox.

-3, B: “عربيٌّۗ” is fixed now, the second one looks like software issue, too. The iqlab mark is tricker, could you please send me the actual text string (e.g. in a .txt file), so I can test it.

Please let me know if you want to test the pre-release version.

Original comment by: khaledhosny

**Comment by khaledhosny** [comment]
- **labels**:  --> Quran
- **status**: open --> pending
- **assigned_to**: Khaled Hosny
- **milestone**:  --> v1.0

Original comment by: khaledhosny

**Comment by khaledhosny** [comment]
جزاكم الله خيرا.
الملف الأصلي مع الأسف لقد ضاع لفساد external hardisk.
و ها أنا أجرب إعادة كتابته مرة أخرى، و لكن الأن أترك كتابة ما على عادة المصاحف الإندونيسية لصعوبتها (استخدمت WordArt ل Microsoft Word 2010 لتصوير العلامات الخاصة للمصاحف الإندونيسية). المثال علامة الإقلاب على عادة المصافحف الإندونيسية كتبتها مستخدمة WordArt حتى أستطيع أن أضعها فى موضعها.
و فى الملف الجديد أجرب أيضا استخدام Amiri Quran فى Microsoft Word 2010 و Amiri QuranWeb فى ملف html.
بالنسبة لAmiri QuranWeb فالأحرف تظهر متقاطعة فى Mozilla Firefox 17.0.1 English و في Opera تظهر صحيحة ولكن مع وجود الدائرة فى بعض علامة الوقف.
هذا، و على كل حال، فجهودكم مشكورة جدا.

Original comment by: msrosyidi

**Comment by khaledhosny** [comment]
هذه نسخة من ملف Word بها بعض التصويبات:
- ”مَجۡر۪ىـٰهَا“ صوابها هكذا ”مَجۡر۪ىٰهَا“، الألف الصغيرى فوق الألف اللينة مباشرة بدون تطويل.
- ”عَلَٰى“ صوابها هكذا ”عَلَىٰ“، الألف الصغيرة على الألف اللينة وليست على اللام.
- ”أَعۡجَمِيّاࣰ“ صوابها هكذا ”أَعۡجَمِيࣰّا“، التنوين يكون فوق الشدة لا الألف (عمومًا، الأصوب أن يكون تنوين النصب على الحرف المنون لا على الألف). التنوين المتتابع أضيف إلي يونيكود في ٢٠١٢ لذا لن يعمل هذا مع الإصدارات الحالية من Word للأسف، لكن يعمل بشكل صحيح مع Firefox.
- ”ءَا۬عۡجَمِيࣱّ وَ عَرَبِيࣱّۗ “ نفس الشيء، Word لا يدعم التنوين المتتابع.
- مشكلة الدائرة المنقوطة تحت علامات الوقف هي أيضا مشكلة في Word وفي محرك الخطوط الذي تستخدمه ميكروسوفت عموما (لذا تجدها في البرامج الأخرى مثل Opera)، ميزة Firefox أنه يستخدم محرك خطوط مستقل لا يعاني من هذه المشكلة. لا تظهر هذه المشكلة مع Quran In Word Ver 1.3 لأنه يستخدم خطا غير قياسي.

مشكلة التقطع في Firefox بسبب عيب في ملف الخط لم أنتبه له، سأحاول إصلاحه.

Original comment by: khaledhosny

**Comment by khaledhosny** [comment]
جزاكم الله خيرا على ما نبهتنيه من الأخطاء فى كيفية كتابتي بعض الكلمات.
و يسرني جدا بإخباركم إياي بعض الترقية فى يونيموك 2012.

إذا، المشكلات فى MS Word مما لا يمكن إصلاحها إلا بإصلاح من ميكروسوت للبرنامج نفسه؟

أنتظر إصلاح المشكلة الموجودة فى Firefox.

Original comment by: msrosyidi

**Comment by khaledhosny** [comment]
الملفا ت المرفقة تحل مشكلة فيرفكس، أرجو تجربتها. أما مشكلة وورد فلا حل لها إلا من ميكروسوفت للأسف.

Original comment by: khaledhosny

**Comment by khaledhosny** [comment]
لقد جربت بالأيات التي كتبتها سابقا بعد إصلاح كيفية كتابتها، فتظهر الأيات - و الحمد لله - صحيحة بلا تقاطع بين الأحرف في فيرفوكس.
و هذه الصورة التي أخذتها مستخدما PrintScreen فى الملف المرفق.
فما أجملَ هذا الخط!
جزاكم الله خيرا و بارك لكم فى جميع أموركم.

Original comment by: msrosyidi

**Comment by khaledhosny** [comment]
- **status**: pending --> closed

Original comment by: khaledhosny

**Comment by khaledhosny** [comment]
I'm sorry I open again this just for reporting only.
This screenshot I take from the same file above "Tajribah Amiri-Quran.htm" opened using Firefox 21.0. I've tried using Amiri 0.105 and 0.106 and the result is same.
I'm not sure this issue is from browser support, but the screenshot I attached in January above using the older version of firefox display correctly.

Original comment by: msrosyidi

**Comment by khaledhosny** [comment]
This is a bug (regression) in the font layout engine used by Firefox, I discovered it few weeks ago and should be fixed in the next release.

Original comment by: khaledhosny

**Comment by khaledhosny** [comment]
Thanks.
That what I think after opened using Opera, Google Chrome, Safari and IE that display correctly, but how about dotted circle under waqf sign when opened using Opera, Google Chrome, Safari and IE? Can it be fixed?

Thanks and I'm sorry.

Original comment by: msrosyidi

**Comment by msrosyidi** [comment]
Oh, it is moved here. But unfortunately I have lost all the document written many years ago.

**Comment by khaledhosny** [comment]
The original tracker still open, see the link above.
