### ISSUE TITLE
Jawi nya dots

### ISSUE THREAD

**Issue by dscorbett** [aliftype/amiri#69]
[According to Unicode](http://www.unicode.org/versions/Unicode8.0.0/ch09.pdf#28), U+06BD ARABIC LETTER NOON WITH THREE DOTS ABOVE “displays with the three dots _below_ the letter pointing downward when it is in the initial or medial position”, but in Amiri, the three dots below the letter point upward.

**Comment by khaledhosny** [comment]
Thanks for reporting this.
