### ISSUE TITLE
مشكلة فى كتابة حرف الطاء مع حرف اللام 

### ISSUE THREAD

**Issue by ghost** [aliftype/amiri#72]
جزاكم الله كل خير على هذا المجهود الرائع و أتمنى لك كل التوفيق

لقد أختبرت خط الرقعة عارف و هى خط رائع و لكن عند كتابة كلمة مثل طلعت أجد إن حرف الطاء قد أختفى من الكلمة

رجاء تصحيح هذة العلة و جزاكم الله كل خير

ملحوظة : لقد أختبرت خط الرقعة عارف على برنامج اﻷنكسكيب 

سلام عليكم

أحمد ضياء

**Comment by khaledhosny** [comment]
شكرا لك، لكن رجاء الإبلاغ عن مشاكل خط الرقعة [هنا](https://github.com/khaledhosny/aref-ruqaa/issues).

لا تظهر معي هذه المشكلة مع إنكسكيب، الرجاء أخذ صورة للمشكلة، و توضيح إصدارة البرنامج و نظام التشغيل.
