### ISSUE TITLE
Improve rendering of ARABIC LETTER HEH GOAL (U+06C1) when typesetting Urdu

### ISSUE THREAD

**Issue by deepakjois** [aliftype/amiri#74]
<img width="340" alt="screenshot 2015-09-29 14 39 53" src="https://cloud.githubusercontent.com/assets/5342/10170916/e7d552a8-66f4-11e5-986d-dba865e5db3c.png">

This is regarding the rendering of Unicode character ARABIC LETTER HEH GOAL (U+06C1) with Amiri font. The attached screenshot shows three different glyph renderings for three common Urdu words containing U+06C1.  The top line is in a Nastaliq font, the second one in the default OS X font for Urdu, and the third for Amiri.

As you can see, the Amiri version differs significantly from the other two. In some cases (like in the middle word ‘ہے’), the rendering is the same as for ARABIC LETTER HEH DOACHASHMEE (U+06BE), which can be really confusing. Is there a good reason for this?

The examples in the screenshots are for renderings of words where U+06C1 appears at the end, or the beginning of a sequence. I can provide examples of words with U+06C1 in the middle of the sequence, if required. But it has the same problem.

I think it affects Urdu readability significantly, to have this rendering. This is probably the only complaint that I have with Amiri currently, which prevents me from using it more when typesetting Urdu. Is it possible to fix?

**Comment by deepakjois** [comment]
It seems that I was using an older version of the font. I have installed 0.108 and I can see the fixes. I saw that you decided to leave the initial form unchanged. Please do consider changing it if you can. But this is a pretty big improvement already.

**Comment by khaledhosny** [comment]
I’ll keep this open to track the initial form change, if I manage to get a form that I find acceptable for Naskh (Urdu not having much of a tradition in using Naskh does not help).

**Comment by khaledhosny** [comment]
I think the current initial form is fine and I’m sticking with it, I think the dotless-beh-with-a-comma is just a stylistic Nastaliq choice not orthographic one, and I have seen Arabic text set in Nasstaliq where this form is used for Arabic Heh.
