### ISSUE TITLE
Add glyph U+0604 ARABIC SIGN SAMVAT

### ISSUE THREAD

**Issue by deepakjois** [aliftype/amiri#75]
Seems to be missing in Amiri, unless I am mistaken.

Unicode Working Group proposal: http://www.unicode.org/L2/L2009/09144r3-arabic-samvat.pdf

**Comment by khaledhosny** [comment]
Amiri lacks support for many newly added Arabic characters inn Unicode that I want to Added at some point, but I can prioritise characters people actually need, so do you particularly need this symbol?

**Comment by deepakjois** [comment]
I can’t say I need it right away. I imagine it won’t be needed in regular usage of Urdu either.

It is more useful in academic writing, research etc. where one might refer to Saka dates for historical accuracy and precision. If it helps you prioritise, I _might_ need it in 4-5 months :), when I have to write a paper of some kind.

**Comment by deepakjois** [comment]
Talking about prioritization, I would take #74 any day over this.
