### ISSUE TITLE
تقطع الحروف عند استخدام ضبط الكشيدة

### ISSUE THREAD

**Issue by hubaishan** [aliftype/amiri#76]
عند استخدام ضبط كشيدة في word 2007-2016 يحصل تقطع في الحروف في بعض العبارات
![2016-02-07 21_18_56-](https://cloud.githubusercontent.com/assets/2285457/12874220/9321f844-cde0-11e5-87d8-d6d1796ef79d.png)

**Comment by khaledhosny** [comment]
ضبط الكشيدة في وورد لا يعمل مع الخط الأميري، و لا حل حاليًا سوى استعمال الضبط بدون كشيدة.
