### ISSUE TITLE
تراكب الحركات عند تراكب الأحرف المشكَّلة

### ISSUE THREAD

**Issue by anasram** [aliftype/amiri#77]
تراكب الأحرف المضبوطة بالشكل يعني غالباً تراكب الحركات أيضاً، وبالتالي تضعف —بل تختفي ربما— بصرياً علاقة الاقتران بين الحركة والحرف الذي يحملها.
أعتقد أنه ينبغي إلغاء تراكب الأحرف عند تشكيلها. 
مثلاً:
![default](https://cloud.githubusercontent.com/assets/12219238/15016363/542d553e-1219-11e6-8fde-32418529dbf4.png)

![default](https://cloud.githubusercontent.com/assets/12219238/15016384/6a2e559a-1219-11e6-8cbe-3cff2a2ceb4a.png)

**Comment by khaledhosny** [comment]
<div dir="rtl">
مؤقتا يمكنك استخدام الواصلة صفرية العرض (U+200D) لكسر التراكيب غير المرغوب فيها.
</div>
