### ISSUE TITLE
ظهور الكسرة تحت الحرف المشدد بدلاً من الشدة

### ISSUE THREAD

**Issue by anasram** [aliftype/amiri#79]
<p dir="rtl">
عادة، في الحروف المشددة ترسم الكسرة تحت الشدة لا تحت الحرف المشدد، في حين يرسمها الخط تحت الحرف.
أعتقد أن الصواب أن ترسم تحت الشدة مباشرة.
</p>

![default](https://cloud.githubusercontent.com/assets/12219238/15016906/f33cb5a0-121b-11e6-8840-a046132c99d8.png)

**Comment by khaledhosny** [comment]
<div dir="rtl">
الشائع في الكسرة مع الشدة كان رسمها تحت الحرف و هو في رأيي الموضع المنطقي لها لأنها حركة للحرف و ليس للشدة فالأولى أن ترسم تحته. إلى أن غيرت هذا مطبعة بولاق بناء على نصيحة من أحمد زكي باشا، و لكونه الأبسط تقنيًا.
يدعم الخط الأميري وضع الكسرة تحت الشدة باستخدام خاصية ss05 الاختيارية، راجع توثيق الخط:
</div>

https://github.com/khaledhosny/amiri-font/blob/master/documentation/documentation-arabic.pdf

**Comment by anasram** [comment]
> <p dir="rtl"> ولكونه الأبسط تقنيًا.</p>

<p dir="rtl">والأهم بصرياً:</p>

> <p dir="rtl">وإذا كان الحرف مشدداً مكسوراً، وضعنا فوقه علامة الشدة ( ّ) وتحتها مباشرة علامة الكسرة ( ِ) وذلك **منعاً لاضطراب العين في مراعاة ما فوق الحرف وما تحته في آنٍ واحد**، فضلاً عن أن المطابع قد تتزحزح فيها الكسرة عن الموضع المتحتم لها، فيحدث عن ذلك بعض الاختلاط الذي يجب تلافيه. وبما أن الكسرة يجب دائماً وضعها من الأسفل فهي في هذه الحالة في مكانها تحت الشدة التي نابت عن الحرف المدغم. نعم إن في ذلك بعض التسامح، ولكن الفائدة منه ظاهرة للعيان.</p>
> 
> — من كتابه: [الترقيم وعلاماته في اللغة العربية](http://www.hindawi.org/books/82047270/)

## 

> <p dir="rtl"> راجع توثيق الخط:</p>
> 
> https://github.com/khaledhosny/amiri-font/blob/master/documentation/documentation-arabic.pdf

<p dir="rtl">يبدو الملف معطوباً!</p>

<p dir="rtl">سؤال على الهامش: كيف تمكنت من عرض النص في مداخلتك من اليمين لليسار؟</p>

**Comment by khaledhosny** [comment]
<div dir="rtl">
لكل وجهة نظره، لكني أفضل الموضع التقليدي لأنه المنطقي في رأيي، و الخط يدعم الاثنين.
أستخدم وسوم HTML مثل:
</div>

```
<div dir="rtl">
…
</div>
```

**Comment by khaledhosny** [comment]
<div dir="rtl">
لا مشكلة في الملف هنا.
</div>
