### ISSUE TITLE
عدم احتواء الراء الرحمانية للحرف الذي يليها

### ISSUE THREAD

**Issue by anasram** [aliftype/amiri#80]
<p dir="rtl">
عند استخدام الراء الرحمانية، أعتقد أنه ينبغي دائماً احتواءها للحرف الذي يليها، أو عدم استخدام الراء الرحمانية أساساً..
جرب مثلاً عبارة (مرة)، يجب في هذه الحالة إظهار التاء المربوطة محمولة على الراء، وإلا فالأولى الحفاظ على الراء بشكلها التقليدي.
</p>

![default](https://cloud.githubusercontent.com/assets/12219238/15048115/b9653ed0-12f0-11e6-957b-752a01f08510.png)

**Comment by khaledhosny** [comment]
<div dir="rtl">
لم تصمم هذه الراء في الخط الأميري لتحتوي الحروف التالية لها، و في الصورة الموضع الحالي أفضل شكلا من المقترح.
</div>

**Comment by anasram** [comment]
<p dir="rtl">
هذه عينة من نصوص وردت فيها الراء الرحمانية في كراسة (قواعد الخط العربي) للخطاط هاشم محمد البغدادي:
</p>

![41](https://cloud.githubusercontent.com/assets/12219238/15295283/6274d8e6-1b98-11e6-8100-2d0b205dac01.png)
![45](https://cloud.githubusercontent.com/assets/12219238/15295303/8e47c30c-1b98-11e6-8b0e-16f5c45188f0.png)
![48](https://cloud.githubusercontent.com/assets/12219238/15295323/a29b144e-1b98-11e6-8e66-4a173a2f14d7.png)

**Comment by khaledhosny** [comment]
<div dir="rtl">
أعرف هذا، لكن التصميم في الخط الأميري لا يناسبها و لا أريد تغييره.
</div>
