### ISSUE TITLE
اقتراح رسم رأس الآية الشائع في مصحف المدينة المنورة

### ISSUE THREAD

**Issue by anasram** [aliftype/amiri#81]
أقترح اعتماد الرسم الشائع لرأس الآية كما هو في مصحف المدينة المنورة بدلاً الرسم الحالي المعتمد في الخط.
![default](https://cloud.githubusercontent.com/assets/12219238/15048655/13eae862-12f3-11e6-9acd-c8b19539015e.png)

**Comment by khaledhosny** [comment]
<div dir="rtl">
الرسم الآخر أصغر بكثير و لن يناسب أرقام الأميري، أيضًا أفضل رسم الأميري فهو ما يستخدمه الأزهر في مصاحفه منذ أول مصحف.
</div>
