### ISSUE TITLE
funny ligatures with the latest TeXLive 2016

### ISSUE THREAD

**Issue by ralessi** [aliftype/amiri#83]
Hi,

I think there may be an issue with the latest texlive 2016, Amiri and LuaLaTeX, but I can't say whether it is Amiri or luaotfload related, nor I can't really assess the extent of this issue I just discovered.

This mwe:

```
\documentclass[12pt]{article}

\usepackage{fontspec}

\newfontfamily\arabicfont[Script=Arabic]{Amiri}

\begin{document}

\textdir TRT\arabicfont
اَلحِمَارُ، اَلجَدِيدُ، اَلحَارِثُ.

\end{document}
```

gives me this, where the last two words are obvioulsy wrong:
![amiri](https://cloud.githubusercontent.com/assets/389498/15871128/4af57fd8-2cf3-11e6-80f3-e164c4e54a38.png)

TeXLive 2015 didn't have this issue.

By the way, Amiri is so beautiful! Many, many thanks for this masterpiece.

Robert

**Comment by khaledhosny** [comment]
Looks like a luaotfload bug, the font did not change recently. You can check with XeTeX, if it has the same issue then that is a font bug.

**Comment by ralessi** [comment]
Thank you for your answer.  I just tried this with XeLaTeX, which works:

```
\documentclass[12pt]{article}

\usepackage{fontspec}

\newfontfamily\arabicfont[Script=Arabic]{Amiri}

\usepackage{polyglossia}
\setdefaultlanguage{arabic}

\begin{document}
اَلحِمَارُ، اَلجَدِيدُ، اَلحَارِثُ.
\end{document}
```

I will file a bug report for luaotfload.
