### ISSUE TITLE
خطأ في رسم كلمة فادارأتم

### ISSUE THREAD

**Issue by munzirtaha** [aliftype/amiri#85]
السلام عليكم
لاحظت وجود خطأ أو على الأقل رسم مختلف لما يوجد في مصحف المدينة ورد في كلمة فادارأتم في سورة البقرة في المصحف الذي قمت بتحميله من
https://bitbucket.org/khaledhosny/quran.git
وحبذا أخي خالد لو نقلت هذا المستودع ليكون جوار مشروع الخط القرآني بحيث نستطيع إضافة العلل في مكان واحد.

وردت الكلمة بدون الألف الخنجرية وبدون السكون، وقد حاولت رسمها كما هو مرفق في الشكل باللونين الأسود والأحمر وظهرت مسافة زائدة بين الهمزة والألف في حالة التلوين

وقد استخدمت الألف المنخفضة
subscript alef U+656
في رسمها ولست متأكدا إن كانت هذه الألف وضعت لهذا الغرض أم لغيره في الأصل

![screenshot_20160623_145503](https://cloud.githubusercontent.com/assets/2936425/16302764/9713bb50-3955-11e6-93b7-cbb722151f59.jpeg)

**Comment by khaledhosny** [comment]
<div dir="rtl">
نقلت المستودع إلى:
</div>

https://github.com/khaledhosny/quaran-data

<div dir="rtl">
النص الذي أستخدمه يعتمد رسم مصحف الأزهر الذي طُبع أول مرة عام ١٣٣٧ ه‍ (معتمدا على طبعته الرابعة المطبوعة عام ١٣٨٨ ه‍). و قد راجعته الآن و الهمزة مسكنة لكن لا ألف تحتها و يبدو أن السكون سقط مني سهوا في مرحلة ما لأنني أذكر مراجعة تلك الكلمة تحديدًا لما لاحظت أن الهمزة بلا ألف، و قد أعدته الآن.
<br/>
<br/>
أما التلوين فلا أظنه عيب في الخط بل في البرنامج المستخدم إذ كثير من البرامج لا تتعامل مع التلوين بصورة صحيحة و تقطع النص الملون إلى أجزاء و تعامل كل جزء على حدة. لا أعرف إلا برنامجين يتعاملان مع التلوين بشكل صحيح؛ فيرفكس و Pango (بالإضافة لإصدارة سكريبس القادمة، إن دمجوا دعم العربية).
</div>

**Comment by khaledhosny** [comment]
<div dir="rtl">
الألف الخنجرية السفلى قد تكون مناسبة هنا بصريًا، لكن لاحظ أن هذه الألف تستخدم في المصاحف التركية و الشرق آسيوية للكسر المتبوع بياء محذوفة، فمثلا ”بِهِۦ“ تكتب ”بِهٖ“.
</div>

**Comment by khaledhosny** [comment]
[رابط للصفحة في المصحف المذكور](https://archive.org/stream/mushafElMesaha#page/n13/mode/1up)

**Comment by munzirtaha** [comment]
من أسند فقد أحال ومن أحال فقد برئ
وحبذا لو تضع هذا الوصف للمصحف المعتمد في صفحة المشروع مع رابطه
وجزاك الله خيرا على جهودك الرائعة وننتظر إصدار سكريبس بشوق

**Comment by khaledhosny** [comment]
<div dir="rtl">
أضفت فقرة صغيرة في صفحة المشروع.
</div>

**Comment by muhammed-ahmad** [comment]
بالنسبه لهذا الرابط:
> [رابط للصفحة في المصحف المذكور](https://archive.org/stream/mushafElMesaha#page/n13/mode/1up)

أود التنبيه على أنه للطبعه الاولى من المصحف, نرجو التعديل ليشير للطبعه الثانيه -والتي كما تعلم بها تصحيحات للطبعه الاولى-
فمثلا هذا رابط لنفس الصفحه في الطبعه الثانيه-ملون-:
https://archive.org/details/MmSL7H/MmSL7HD/page/n13/mode/1up?view=theater
او هذا -ابيض واسود-:
https://archive.org/details/MmSL7H/MmSL7HB/page/n13/mode/1up?view=theater
