### ISSUE TITLE
الحرف الملون بعد حرف مشكل يسبب تقطيعه

### ISSUE THREAD

**Issue by munzirtaha** [aliftype/amiri#86]
إذا قمت بتلوين حرف بعد حرف عليه إحدى علامات التشكيل فإن مسافة زائدة تظهر مما يقطع الكلمة، وهذه المشكلة تظهر في الخط الأميري وخط الرقعة عارف لكنها لاتظهر في خط جوجل "نوتو نسخ" على سبيل المثال
![screenshot_20160623_164001](https://cloud.githubusercontent.com/assets/2936425/16305141/2ffc2ef0-3961-11e6-848c-db0b67da493c.jpeg)

**Comment by khaledhosny** [comment]
<div dir="rtl">
ما البرنامج المستخدم؟
</div>

**Comment by munzirtaha** [comment]
libreoffice-fresh 5.1.3-2

**Comment by khaledhosny** [comment]
<div dir="rtl">
هذه علة في ليبرأوفيس، الجزء الملون من النص يعالج منفصلا و بالتالي أي خصائص أوبن تيب بين الجزء الملون و غير الملون (سواء خصائص استبدال أو تموضع) لن تُطبق. في الخطوط البسيطة لن تظهر المشكلة أغلب الوقت (لكن جرب تلوين لام ”لا“ مثلا و ستظهر المشكلة مع أي خط) لكن في الخطوط المتقدمة ستظهر المشكلة بسهولة كما ترى.
</div>

**Comment by munzirtaha** [comment]
بالنسبة لحرف اللام مع الألف أتصور حدوث مشكلة بسبب تركيبها المعقد لكني لم أستوعب (غالبا بسبب جهلي بتصميم الخطوط) حدوث المشكلة مع التراكيب البسيطة مثل كلمة "لن" في الخط الأميري بينما تجنبها خط "نوتو" لأن كلا الخطين نسخ ورسم الأحرف متقارب فهل هناك حيلة استخدمها الأستاذ قوقل للالتفاف حول هذه العلة في برنامج ليبرا أوفيس؟ وهل هناك رابط لهذه العلة؟

**Comment by khaledhosny** [comment]
<div dir="rtl">
لا حيل مستخدمة. ليبرأوفيس ينظر إلى الحرف السابق و اللاحق للجزء الملون و بناء عليه يحدد إذا كان الجزء الملون في وسط الكلمة أو أولها أو آخرها. في الخطوط البسيطة مثل نوتو شكل الحرف في وسط الكلمة واحد، الميم مثلا في وسط الكلمة ثابتة سواء كان قبلها حاء أم لام أم غيرها لذا لا يظهر أي اختلاف هنا. في الخطوط المتقدمة مثل الأميري أو رقعة عارف يختلف شكل الحرف و موضعه تبعا للحرف السابق له، لذا تظهر المشاكل مع هذه الطريقة.
</div>

**Comment by munzirtaha** [comment]
وضحت الفكرة شكر الله لك، هل هناك رابط لهذه العلة في ليبرا أوفيس لمتابعتها أو علي الإبلاغ عنها؟

**Comment by khaledhosny** [comment]
<div dir="rtl">
هذه علة للمشكلة العامة، لا العربية تحديدا (مع العربية المشكلة أسوأ):
</div>

https://bugs.documentfoundation.org/show_bug.cgi?id=61444
