### ISSUE TITLE
اختلاف الألوان بين المتشابهات

### ISSUE THREAD

**Issue by munzirtaha** [aliftype/amiri#87]
ألاحظ أنك تضع الألف الخنجرية بلونين مختلفين مثلا في
http://www.amirifont.org/fatiha-colored.html
بلون أسود في "العالمين" وباللون الأرجواني في "صراط" وكأنك تفرق بين كونها بين حرفين متصلين وغير متصلين، ولا أدري علة  هذا التفريق

كذلك كلمة "مهتدين" في البقرة الآية 16 تظهر الميم بلون أرجواني على فايروفكس، فما هو السبب؟

كذلك الياء في "الذي" بلون أرجواني في البقرة 22 بينما الياء في "التي" البقرة 24 تظهر بلون أسود، ولم يتضح لي السبب كذلك.

**Comment by khaledhosny** [comment]
<div dir="rtl">
اختلاف اللون غير مقصود في الحالتين، علة في كود التلوين.
</div>

**Comment by khaledhosny** [comment]
<div dir="rtl">
المثال على الموقع يستخدم نسخة قديمة من الخط، حدثت نسخة الخط المستخدمة و لا يظهر فيها هذا التفريق.
<br/><br/>
ميم ”مهتدين“ غير ملونة عندي، أي أصدارة فيرفكس تستخدم؟
<br/><br/>
ليس في الآيات ٢٢ و ٢٤ من البقرة لا ”الذي“ و لا ”التي“.
</div>

**Comment by munzirtaha** [comment]
يبدو لي أنك استبدلت خط تروتايب بخط الوب لذا اختفت المشكلة، حاولت العثور على خطوط الوب في المستودع حتى أختبر النسخة الحديثة فلم أجدها في
amiri-font/tree/master/webfonts
مع أني أذكر أنها كانت موجودة يوما ما، فهلا وضعتها مجددا؟

كيف لا توجد الذي والتي في الآيتين من سورة البقرة؟!

الذي جعل لكم الأرض فراشا

فاتقوا النار التي وقودها الناس والحجارة

**Comment by khaledhosny** [comment]
<div dir="rtl">
خطوط الوب موجودة في حزمة الإصدارة و ليست في المستودع (لتقليل حجم المستودع)، حتى نسخة woff الحالية لا مشكلة فيها.
<br/><br/>
آسف، كنت أبحث عن كلمات بها الياء الصغيرة إذ ظننت المشكلة بها، لا مشكلة عندي في الكلمتين.
</div>

**Comment by munzirtaha** [comment]
ما زالت العلة الموجودة، رفعت الملف هنا
https://munzirtaha.fedorapeople.org/al-baqarah.html

وهذه صورة ما ظهر لدي

![al-baqarah](https://cloud.githubusercontent.com/assets/2936425/16520499/ff42238a-3f98-11e6-9ea3-5cd6aa9bd068.jpg)

**Comment by khaledhosny** [comment]
<div dir="rtl">
أظن المشكلة في نسخة WOFF القديمة، سبق أن حللت مشكلة قد تسبب هذا، لكن لا أذكر متى. سأحاول إصدار واحدة جديدة قريبة.
</div>

**Comment by munzirtaha** [comment]
لماذا تم إغلاق هذه العلة؟
لم يتم إصدار نسخة جديدة تحل المشكلة بعد
هذه العلة تخص خطوط الوب

**Comment by khaledhosny** [comment]
https://github.com/khaledhosny/amiri-font/releases/tag/0.109
