### ISSUE TITLE
اختلاف ميلان الكاف مع الأحرف غير متناسق 

### ISSUE THREAD

**Issue by munzirtaha** [aliftype/amiri#89]
يتغير ميلان حرف الكاف حسب الحرف الذي يعقبه فتظهر أحيانا بصورة غير متناسقة مثلا في الآية 200 من سورة البقرة ظهرت كلمة 
![2-200-wrong](https://cloud.githubusercontent.com/assets/2936425/16541059/05d95968-4082-11e6-89fa-efebb7b5fcdb.jpeg)
بينما في الأصل
![2-200-correct](https://cloud.githubusercontent.com/assets/2936425/16541061/0e40f872-4082-11e6-838d-224b05bdb65a.jpeg)
بالطبع ليست لي أي خبرة في مسألة الخطوط وجمالها لكنه إحساسي فقط

**Comment by munzirtaha** [comment]
يا ليتك توضح أيضا هنا لم تم إغلاق العلة بعد سنوات من اعتباره تحسينا مقبولا، حتى ولو كان هذا التركيب صحيحا وجميلا في الخط فإن غرض الخط الأميري هو محاكاة الخط الذي كتب به المصحف وليس في المصحف مثل هذا الشكل

**Comment by khaledhosny** [comment]
> يا ليتك توضح أيضا هنا لم تم إغلاق العلة بعد سنوات من اعتباره تحسينا مقبولا

نفس الأسباب المذكورة فی https://github.com/alif-type/amiri/issues/91#issuecomment-721718557

> حتى ولو كان هذا التركيب صحيحا وجميلا في الخط فإن غرض الخط الأميري هو محاكاة الخط الذي كتب به المصحف وليس في المصحف مثل هذا الشكل

الخط الأمیری محاكاة للقاعدة النسخیة الأخیرة لمطبعة بولاق، وقد جرت على هذا القاعدة بعش التغییرات فی السنوات اللاحقة على إصدارها، منها شكل الكاف الأولیة والوسطیة وهو الشكل الحالی فی الخط الأمیری. المصحف الأمیری طبع بقاعدة نسخیة مشتقة من مطبعة بولاق على شكل الكاف القدیم، ومع تغییرات أخرى منسابة لطباعة المصحف كامل الشكل، بعض هذه التغییرات موجود فی الخط الأمیری ولیس كلها للأسباب المذكورة سابقا.
