### ISSUE TITLE
تراكب النون مع الكاف يجعل حركة النون فوق الكاف

### ISSUE THREAD

**Issue by munzirtaha** [aliftype/amiri#91]
مثلا في كلمة 
![correct](https://cloud.githubusercontent.com/assets/2936425/16559698/579ec186-41f7-11e6-9f95-8ccb7bb3e7c0.jpeg) تظهر هكذا 
![wrong](https://cloud.githubusercontent.com/assets/2936425/16559705/64e5f21a-41f7-11e6-96ff-3d2e819fb96b.jpeg)

**Comment by munzirtaha** [comment]
Khaled, can you please elaborate on why you closed this with wontfix for the record, please?

**Comment by khaledhosny** [comment]
It isn’t an error per se, and though not ideal it is still OK. Making any changes to Amiri is prohibitively complex and time consuming, so I’m trying to limit myself to things that must be fixed. If I ever get to redo Amiri, I might consider these good to have issues.
